import { Router } from 'express';
import * as c from './job.controller.js';
import { requireAuth } from '../../middlewares/auth.middleware.js';
import { validate } from '../../middlewares/validate.middleware.js';
import { createSchema, updateSchema, idSchema } from './job.validation.js';
import asyncHandler from '../../utils/asyncHandler.js';
const r = Router();
r.get('/', asyncHandler(c.list));
r.post('/', requireAuth, validate(createSchema), asyncHandler(c.create));
r.patch('/:id', requireAuth, validate(updateSchema), asyncHandler(c.update));
r.post('/:id/submit', requireAuth, validate(idSchema), asyncHandler(c.submit));
r.get('/:slug', asyncHandler(c.detail));
export default r;
