import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Seo from '../../components/common/Seo';
import PageHeader from '../../components/common/PageHeader';
import Button from '../../components/common/Button';
import FormField from '../../components/common/FormField';
import RichTextEditor from '../../components/forms/RichTextEditor';
import MediaUploader from '../../components/forms/MediaUploader';
import TaxonomyFields from '../../components/forms/TaxonomyFields';
import { adminApi } from '../../api/admin.api';
import { apiErrorMessage } from '../../api/http';
import { useToast } from '../../context/ToastContext';

export default function ArticleEditorPage(){const navigate=useNavigate();const toast=useToast();const[loading,setLoading]=useState(false);const[form,setForm]=useState({title:'',summary:'',bodyHtml:'',articleType:'news',primaryCategoryId:null,primaryAreaId:null,tagIds:[],thumbnailMediaId:null,status:'draft',scheduledAt:'',sourceNote:''});const change=(k,v)=>setForm(c=>({...c,[k]:v}));const submit=async(e)=>{e.preventDefault();setLoading(true);try{await adminApi.createArticle({...form,thumbnailMediaId:form.thumbnailMediaId?._id||null,scheduledAt:form.scheduledAt||null});toast.success('Đã tạo bài viết.');navigate('/quan-tri/bai-viet')}catch(error){toast.error(apiErrorMessage(error))}finally{setLoading(false)}};return <section><Seo title="Tạo bài tin tức"/><PageHeader eyebrow="Biên tập" title="Tạo bài tin tức mới" description="Bài có thể lưu nháp, chờ duyệt, lên lịch hoặc xuất bản tùy quyền tài khoản."/><form className="editor-card stack-form" onSubmit={submit}><div className="form-grid form-grid--2"><FormField label="Loại bài"><select value={form.articleType} onChange={e=>change('articleType',e.target.value)}><option value="news">Tin tức</option><option value="analysis">Phân tích</option><option value="guide">Hướng dẫn</option><option value="interview">Phỏng vấn</option><option value="photo">Ảnh</option><option value="sponsored">Tài trợ</option></select></FormField><FormField label="Trạng thái"><select value={form.status} onChange={e=>change('status',e.target.value)}><option value="draft">Bản nháp</option><option value="pending_review">Chờ duyệt</option><option value="approved">Đã duyệt</option><option value="scheduled">Lên lịch</option><option value="published">Xuất bản</option></select></FormField></div><FormField label="Tiêu đề" required><input value={form.title} onChange={e=>change('title',e.target.value)} required minLength={5}/></FormField><FormField label="Mô tả ngắn"><textarea rows="3" value={form.summary} onChange={e=>change('summary',e.target.value)}/></FormField><FormField label="Nội dung" required><RichTextEditor value={form.bodyHtml} onChange={v=>change('bodyHtml',v)}/></FormField><TaxonomyFields scope="article" categoryId={form.primaryCategoryId} areaId={form.primaryAreaId} tagIds={form.tagIds} onChange={change}/><MediaUploader value={form.thumbnailMediaId} onChange={v=>change('thumbnailMediaId',v)}/>{form.status==='scheduled'?<FormField label="Thời gian xuất bản"><input type="datetime-local" value={form.scheduledAt} onChange={e=>change('scheduledAt',e.target.value)} required/></FormField>:null}<FormField label="Nguồn và ghi chú"><textarea rows="4" value={form.sourceNote} onChange={e=>change('sourceNote',e.target.value)}/></FormField><Button type="submit" loading={loading}>Tạo bài viết</Button></form></section>}
