import { useState } from 'react';
import { useLocation, useNavigate, useSearchParams } from 'react-router-dom';
import Seo from '../../components/common/Seo';
import PageHeader from '../../components/common/PageHeader';
import Button from '../../components/common/Button';
import FormField from '../../components/common/FormField';
import RichTextEditor from '../../components/forms/RichTextEditor';
import MediaUploader from '../../components/forms/MediaUploader';
import TaxonomyFields from '../../components/forms/TaxonomyFields';
import { communityApi } from '../../api/content.api';
import { apiErrorMessage } from '../../api/http';
import { useToast } from '../../context/ToastContext';
import { COMMUNITY_TYPES } from '../../utils/constants';

export default function CommunityEditorPage() {
  const [params] = useSearchParams(); const editingId = params.get('edit'); const location = useLocation(); const navigate = useNavigate(); const toast = useToast();
  const source = location.state?.item || {};
  const [form, setForm] = useState({ title: source.title || '', summary: source.summary || '', bodyHtml: '', postType: 'discussion', primaryCategoryId: source.primaryCategoryId?._id || source.primaryCategoryId || null, primaryAreaId: source.primaryAreaId?._id || source.primaryAreaId || null, tagIds: source.tagIds || [], thumbnailMediaId: source.thumbnailMediaId || null, allowComments: true, incidentTime: '', locationText: '', rating: '' });
  const [loading, setLoading] = useState(false);
  const change = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const payload = () => ({ ...form, thumbnailMediaId: form.thumbnailMediaId?._id || form.thumbnailMediaId || null, incidentTime: form.incidentTime || null, rating: form.rating ? Number(form.rating) : null, bodyHtml: form.bodyHtml || undefined });
  const save = async (submitAfter = false) => { setLoading(true); try { let content; if (editingId) content = await communityApi.update(editingId, payload()); else content = await communityApi.create({ ...payload(), bodyHtml: form.bodyHtml }); if (submitAfter) await communityApi.submit(content?._id || editingId); toast.success(submitAfter ? 'Đã lưu và gửi bài đi duyệt.' : 'Đã lưu bản nháp.'); navigate('/tai-khoan/bai-viet'); } catch (error) { toast.error(apiErrorMessage(error)); } finally { setLoading(false); } };
  return <section className="page-section"><Seo title={editingId ? 'Sửa bài cộng đồng' : 'Đăng bài cộng đồng'} /><div className="container container--narrow"><PageHeader eyebrow="Cộng đồng" title={editingId ? 'Chỉnh sửa bài viết' : 'Tạo bài viết cộng đồng'} description="Nội dung cần rõ ràng, đúng khu vực và tuân thủ quy định cộng đồng." /><div className="editor-card"><div className="form-grid form-grid--2"><FormField label="Loại bài" required><select value={form.postType} onChange={(event) => change('postType', event.target.value)}>{Object.entries(COMMUNITY_TYPES).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></FormField>{form.postType === 'review' ? <FormField label="Điểm đánh giá"><select value={form.rating} onChange={(event) => change('rating', event.target.value)}><option value="">Chọn điểm</option>{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value}/5</option>)}</select></FormField> : null}</div><FormField label="Tiêu đề" required><input value={form.title} onChange={(event) => change('title', event.target.value)} required minLength={5} maxLength={250} /></FormField><FormField label="Mô tả ngắn"><textarea rows="3" value={form.summary} onChange={(event) => change('summary', event.target.value)} maxLength={1000} /></FormField><FormField label="Nội dung" required={!editingId}><RichTextEditor value={form.bodyHtml} onChange={(value) => change('bodyHtml', value)} /></FormField><TaxonomyFields scope="community" categoryId={form.primaryCategoryId} areaId={form.primaryAreaId} tagIds={form.tagIds} onChange={change} areaRequired={form.postType === 'report'} />{form.postType === 'report' ? <div className="form-grid form-grid--2"><FormField label="Thời gian xảy ra"><input type="datetime-local" value={form.incidentTime} onChange={(event) => change('incidentTime', event.target.value)} /></FormField><FormField label="Địa điểm cụ thể"><input value={form.locationText} onChange={(event) => change('locationText', event.target.value)} maxLength={500} /></FormField></div> : null}<MediaUploader value={form.thumbnailMediaId} onChange={(value) => change('thumbnailMediaId', value)} /><label className="checkbox-row"><input type="checkbox" checked={form.allowComments} onChange={(event) => change('allowComments', event.target.checked)} /><span>Cho phép thành viên bình luận.</span></label>{editingId ? <div className="editor-warning">Server chưa có API lấy nội dung HTML của bản nháp. Chỉ các trường bạn nhập lại trên trang này được cập nhật.</div> : null}<div className="form-actions"><Button variant="outline" loading={loading} onClick={() => save(false)}>Lưu bản nháp</Button><Button loading={loading} onClick={() => save(true)}>Lưu và gửi duyệt</Button></div></div></div></section>;
}
