import { useState } from 'react';
import Seo from '../../components/common/Seo';
import PageHeader from '../../components/common/PageHeader';
import Button from '../../components/common/Button';
import FormField from '../../components/common/FormField';
import MediaUploader from '../../components/forms/MediaUploader';
import { articleApi } from '../../api/content.api';
import { apiErrorMessage } from '../../api/http';
import { useTaxonomy } from '../../context/TaxonomyContext';
import { useToast } from '../../context/ToastContext';

export default function NewsTipPage() {
  const { areas } = useTaxonomy(); const toast = useToast(); const [media, setMedia] = useState(null); const [loading, setLoading] = useState(false); const [done, setDone] = useState(false); const [form, setForm] = useState({ title:'', description:'', areaId:'', eventTime:'', source:'', contactName:'', contactPhone:'', contactEmail:'', allowContact:false }); const change=(k,v)=>setForm((c)=>({...c,[k]:v}));
  const submit=async(event)=>{event.preventDefault();setLoading(true);try{await articleApi.submitTip({...form,areaId:form.areaId||null,eventTime:form.eventTime||null,mediaIds:media? [media._id]:[]});setDone(true);toast.success('Đã gửi thông tin tới Ban biên tập.');}catch(error){toast.error(apiErrorMessage(error));}finally{setLoading(false);}};
  return <section className="page-section"><Seo title="Gửi tin cho Ban biên tập" /><div className="container container--narrow"><PageHeader eyebrow="Nguồn tin cộng đồng" title="Gửi tin cho Ban biên tập" description="Cung cấp sự kiện, hình ảnh hoặc thông tin đáng chú ý. Ban biên tập sẽ xác minh trước khi xuất bản." />{done ? <div className="success-panel form-card"><h2>Cảm ơn bạn đã cung cấp thông tin</h2><p>Ban biên tập sẽ xem xét và liên hệ nếu cần xác minh thêm.</p></div> : <form className="editor-card stack-form" onSubmit={submit}><FormField label="Tiêu đề thông tin" required><input value={form.title} onChange={(e)=>change('title',e.target.value)} minLength={10} maxLength={250} required /></FormField><FormField label="Nội dung sự việc" required><textarea rows="8" value={form.description} onChange={(e)=>change('description',e.target.value)} minLength={20} maxLength={10000} required /></FormField><div className="form-grid form-grid--2"><FormField label="Khu vực"><select value={form.areaId} onChange={(e)=>change('areaId',e.target.value)}><option value="">Chưa xác định</option>{areas.map((a)=><option key={a._id} value={a._id}>{a.name}</option>)}</select></FormField><FormField label="Thời gian xảy ra"><input type="datetime-local" value={form.eventTime} onChange={(e)=>change('eventTime',e.target.value)} /></FormField></div><FormField label="Nguồn thông tin"><textarea rows="3" value={form.source} onChange={(e)=>change('source',e.target.value)} placeholder="Bạn biết thông tin này từ đâu?" /></FormField><MediaUploader label="Ảnh minh họa" value={media} onChange={setMedia} /><h2>Thông tin liên hệ riêng</h2><div className="form-grid form-grid--2"><FormField label="Họ tên"><input value={form.contactName} onChange={(e)=>change('contactName',e.target.value)} /></FormField><FormField label="Số điện thoại"><input value={form.contactPhone} onChange={(e)=>change('contactPhone',e.target.value)} /></FormField><FormField label="Email"><input type="email" value={form.contactEmail} onChange={(e)=>change('contactEmail',e.target.value)} /></FormField></div><label className="checkbox-row"><input type="checkbox" checked={form.allowContact} onChange={(e)=>change('allowContact',e.target.checked)} /><span>Đồng ý để Ban biên tập liên hệ xác minh. Thông tin này không tự động công khai.</span></label><Button type="submit" loading={loading}>Gửi thông tin</Button></form>}</div></section>;
}
