import { Router } from 'express';
import * as c from './moderation.controller.js';
import * as leadController from '../leads/lead.controller.js';
import { requireAuth } from '../../middlewares/auth.middleware.js';
import { requireRole } from '../../middlewares/role.middleware.js';
import { ADMIN_ROLES } from '../../constants/roles.js';
import asyncHandler from '../../utils/asyncHandler.js';
const r = Router();
r.use(requireAuth, requireRole(...ADMIN_ROLES));
r.get('/dashboard', asyncHandler(c.dashboard));
r.get('/moderation/queue', asyncHandler(c.queue));
r.post('/contents/:id/approve', asyncHandler(c.approve));
r.post('/contents/:id/request-revision', asyncHandler(c.requestRevision));
r.post('/contents/:id/reject', asyncHandler(c.reject));
r.post('/contents/:id/hide', asyncHandler(c.hide));
r.post('/contents/:id/restore', asyncHandler(c.restore));
r.get('/users', asyncHandler(c.users));
r.patch('/users/:id/status', asyncHandler(c.userStatus));
r.get('/reports', asyncHandler(c.reports));
r.patch('/reports/:id', asyncHandler(c.report));
r.get('/leads', asyncHandler(leadController.adminList));
r.get('/leads/:id', asyncHandler(leadController.detail));
r.patch('/leads/:id', asyncHandler(leadController.adminUpdate));
export default r;
