import Project from '../modules/projects/project.model.js';

// 12 dự án mô phỏng dùng để kiểm thử Project Tracker trong môi trường dev/staging.
// Tên, vốn, pháp lý, chủ đầu tư, nhà thầu và tiến độ bên dưới là dữ liệu demo,
// không đại diện cho hồ sơ dự án thực tế ngoài đời.
const definitions = [
  {
    code: 'DTHL-PRJ-001',
    slug: 'tuyen-ket-noi-phia-dong-khu-cnc-hoa-lac',
    name: 'Tuyến kết nối phía Đông Khu Công nghệ cao Hòa Lạc',
    shortName: 'Tuyến kết nối phía Đông Khu CNC',
    projectType: 'transport',
    status: 'construction',
    priority: 'critical',
    progressPercent: 68,
    primaryAreaSlug: 'khu-cong-nghe-cao-hoa-lac',
    areaSlugs: ['khu-cong-nghe-cao-hoa-lac', 'hoa-lac', 'dai-lo-thang-long'],
    locationText: 'Khu Công nghệ cao Hòa Lạc - trục kết nối Đại lộ Thăng Long',
    latitude: 21.0185,
    longitude: 105.5312,
    investor: 'Ban quản lý dự án hạ tầng Hòa Lạc (demo)',
    developer: 'Liên danh phát triển hạ tầng phía Đông (demo)',
    managingAuthority: 'Đơn vị quản lý hạ tầng Hòa Lạc (demo)',
    contractor: 'Liên danh nhà thầu giao thông HL-01 (demo)',
    consultant: 'Tư vấn thiết kế giao thông Hòa Lạc (demo)',
    totalInvestmentVnd: 4200000000000,
    fundingSources: ['Ngân sách đầu tư phát triển (demo)', 'Nguồn vốn hợp pháp khác (demo)'],
    lengthKm: 7.4,
    scaleText: 'Tuyến đường chính dài khoảng 7,4 km, gồm nút giao, hệ thống thoát nước, chiếu sáng và hạ tầng kỹ thuật đồng bộ.',
    approvalDecisionNo: 'DEMO/QD-001',
    approvalDecisionDate: '2025-05-20',
    startDate: '2025-10-01',
    expectedCompletionDate: '2027-03-31',
    description: 'Dự án mô phỏng tuyến kết nối phục vụ kiểm thử quản lý vốn, tiến độ, nhà thầu và dữ liệu công khai của Project Tracker.',
    objectives: 'Tăng năng lực kết nối khu công nghệ cao với trục giao thông chính, giảm thời gian di chuyển và hoàn thiện mạng lưới hạ tầng khu vực.',
    currentUpdate: 'Đang thi công nền đường, cống thoát nước và hai nút giao chính; khối lượng tổng thể ước đạt 68%.',
    risks: 'Nguy cơ chậm bàn giao mặt bằng cục bộ và xung đột hạ tầng kỹ thuật hiện hữu.',
    nextSteps: 'Hoàn tất xử lý nền yếu, chuyển sang thi công kết cấu mặt đường và đồng bộ hệ thống chiếu sáng.',
    isFeatured: true,
    isPublic: true,
    sortOrder: 120,
    milestones: [
      ['Phê duyệt chủ trương và thiết kế cơ sở', 'completed', '2025-06-30', '2025-06-24', 100, 'Hồ sơ demo đã hoàn tất.'],
      ['Hoàn thành giải phóng mặt bằng chính', 'completed', '2026-02-28', '2026-03-10', 100, 'Hoàn thành sau mốc kế hoạch 10 ngày.'],
      ['Thi công nền đường và công trình thoát nước', 'in_progress', '2026-10-31', null, 72, 'Đang triển khai đồng thời nhiều mũi thi công.'],
      ['Hoàn thiện mặt đường và nghiệm thu', 'pending', '2027-03-31', null, 0, 'Chờ hoàn thành các hạng mục chính.'],
    ],
  },
  {
    code: 'DTHL-PRJ-002',
    slug: 'ha-tang-ky-thuat-khu-do-thi-hoa-lac-giai-doan-1',
    name: 'Hạ tầng kỹ thuật Khu đô thị Hòa Lạc - Giai đoạn 1',
    shortName: 'Hạ tầng KĐT Hòa Lạc GĐ1',
    projectType: 'urban',
    status: 'construction',
    priority: 'critical',
    progressPercent: 42,
    primaryAreaSlug: 'khu-do-thi-hoa-lac',
    areaSlugs: ['khu-do-thi-hoa-lac', 'hoa-lac', 'thach-hoa', 'tan-xa'],
    locationText: 'Khu đô thị Hòa Lạc, khu vực Thạch Hòa - Tân Xã',
    latitude: 21.0119,
    longitude: 105.5148,
    investor: 'Ban phát triển đô thị Hòa Lạc (demo)',
    developer: 'Đơn vị phát triển Khu đô thị Hòa Lạc (demo)',
    managingAuthority: 'Cơ quan quản lý phát triển đô thị (demo)',
    contractor: 'Liên danh hạ tầng đô thị HL-02 (demo)',
    consultant: 'Tư vấn quy hoạch và hạ tầng đô thị HL (demo)',
    totalInvestmentVnd: 6800000000000,
    fundingSources: ['Vốn đầu tư phát triển (demo)', 'Vốn huy động hợp pháp (demo)'],
    landAreaHa: 380,
    scaleText: 'San nền, đường nội khu, cấp điện, cấp nước, thoát nước, viễn thông và cảnh quan trên phạm vi khoảng 380 ha.',
    approvalDecisionNo: 'DEMO/QD-002',
    approvalDecisionDate: '2025-08-12',
    startDate: '2026-01-15',
    expectedCompletionDate: '2028-06-30',
    description: 'Dữ liệu mô phỏng dự án hạ tầng kỹ thuật đô thị quy mô lớn để kiểm thử dashboard vốn, milestone và bộ lọc tiến độ.',
    objectives: 'Hình thành khung hạ tầng đồng bộ cho các khu chức năng, nhà ở, dịch vụ và không gian công cộng trong khu đô thị.',
    currentUpdate: 'Đang triển khai san nền khu A, tuyến đường trục số 2 và mạng cấp nước giai đoạn đầu.',
    risks: 'Khối lượng hạ tầng ngầm lớn, cần phối hợp nhiều gói thầu và kiểm soát cao độ san nền.',
    nextSteps: 'Hoàn thiện san nền khu A, khởi công trạm xử lý nước và đấu thầu gói cảnh quan trung tâm.',
    isFeatured: true,
    isPublic: true,
    sortOrder: 115,
    milestones: [
      ['Phê duyệt quy hoạch và tổng mặt bằng', 'completed', '2025-09-30', '2025-09-18', 100, 'Hoàn tất hồ sơ demo.'],
      ['San nền khu A', 'in_progress', '2026-12-31', null, 55, 'Đang thi công theo phân khu.'],
      ['Hoàn thành hạ tầng kỹ thuật khu A', 'pending', '2027-09-30', null, 0, 'Chưa bắt đầu.'],
      ['Nghiệm thu giai đoạn 1', 'pending', '2028-06-30', null, 0, 'Mốc tổng hợp.'],
    ],
  },
  {
    code: 'DTHL-PRJ-003',
    slug: 'trung-tam-doi-moi-sang-tao-hoa-lac',
    name: 'Trung tâm đổi mới sáng tạo Hòa Lạc',
    shortName: 'Trung tâm ĐMST Hòa Lạc',
    projectType: 'technology',
    status: 'tendering',
    priority: 'high',
    progressPercent: 24,
    primaryAreaSlug: 'khu-cong-nghe-cao-hoa-lac',
    areaSlugs: ['khu-cong-nghe-cao-hoa-lac', 'hoa-lac'],
    locationText: 'Khu Công nghệ cao Hòa Lạc',
    latitude: 21.0282,
    longitude: 105.5261,
    investor: 'Trung tâm phát triển đổi mới sáng tạo Hòa Lạc (demo)',
    developer: 'Ban phát triển hệ sinh thái công nghệ (demo)',
    managingAuthority: 'Đơn vị quản lý Khu Công nghệ cao (demo)',
    contractor: 'Đang lựa chọn nhà thầu (demo)',
    consultant: 'Tư vấn thiết kế trung tâm đổi mới sáng tạo (demo)',
    totalInvestmentVnd: 1850000000000,
    fundingSources: ['Vốn đầu tư công (demo)', 'Nguồn xã hội hóa (demo)'],
    landAreaHa: 12.6,
    scaleText: 'Tổ hợp phòng nghiên cứu, không gian làm việc chung, trung tâm trình diễn công nghệ và khu hỗ trợ doanh nghiệp.',
    approvalDecisionNo: 'DEMO/QD-003',
    approvalDecisionDate: '2026-02-18',
    startDate: '2026-11-01',
    expectedCompletionDate: '2028-02-29',
    description: 'Dự án demo mô phỏng trung tâm hỗ trợ nghiên cứu, startup và chuyển giao công nghệ.',
    objectives: 'Tạo không gian thử nghiệm, kết nối doanh nghiệp - viện trường và hỗ trợ thương mại hóa sản phẩm công nghệ.',
    currentUpdate: 'Đã phát hành hồ sơ mời thầu gói xây lắp chính và đang hoàn thiện đánh giá kỹ thuật.',
    risks: 'Tiến độ lựa chọn nhà thầu có thể ảnh hưởng thời điểm khởi công nếu phải làm rõ hồ sơ nhiều vòng.',
    nextSteps: 'Hoàn tất lựa chọn nhà thầu, ký hợp đồng và bàn giao mặt bằng để khởi công.',
    isFeatured: true,
    isPublic: true,
    sortOrder: 110,
    milestones: [
      ['Phê duyệt dự án đầu tư', 'completed', '2026-03-15', '2026-03-08', 100, 'Đã hoàn tất.'],
      ['Lựa chọn tư vấn thiết kế', 'completed', '2026-05-31', '2026-05-26', 100, 'Đã hoàn tất.'],
      ['Lựa chọn nhà thầu xây lắp', 'in_progress', '2026-10-15', null, 65, 'Đang đánh giá hồ sơ.'],
      ['Khởi công xây dựng', 'pending', '2026-11-01', null, 0, 'Chờ kết quả đấu thầu.'],
    ],
  },
  {
    code: 'DTHL-PRJ-004',
    slug: 'cum-nghien-cuu-ky-tuc-xa-dhqg-hoa-lac',
    name: 'Cụm nghiên cứu và ký túc xá Đại học Quốc gia tại Hòa Lạc',
    shortName: 'Cụm nghiên cứu - KTX Hòa Lạc',
    projectType: 'education',
    status: 'construction',
    priority: 'high',
    progressPercent: 55,
    primaryAreaSlug: 'dai-hoc-quoc-gia-ha-noi',
    areaSlugs: ['dai-hoc-quoc-gia-ha-noi', 'hoa-lac'],
    locationText: 'Khu Đại học Quốc gia Hà Nội tại Hòa Lạc',
    latitude: 21.0045,
    longitude: 105.5521,
    investor: 'Ban phát triển cơ sở giáo dục Hòa Lạc (demo)',
    developer: 'Đơn vị quản lý cơ sở đại học (demo)',
    managingAuthority: 'Cơ quan quản lý giáo dục - nghiên cứu (demo)',
    contractor: 'Liên danh xây dựng giáo dục HL-04 (demo)',
    consultant: 'Tư vấn thiết kế campus Hòa Lạc (demo)',
    totalInvestmentVnd: 3200000000000,
    fundingSources: ['Vốn đầu tư phát triển giáo dục (demo)'],
    landAreaHa: 28.4,
    scaleText: 'Các khối phòng thí nghiệm, giảng đường hỗ trợ, ký túc xá, hạ tầng phụ trợ và cảnh quan campus.',
    approvalDecisionNo: 'DEMO/QD-004',
    approvalDecisionDate: '2025-04-02',
    startDate: '2025-09-10',
    expectedCompletionDate: '2027-08-31',
    description: 'Dữ liệu demo cho nhóm dự án giáo dục, phục vụ kiểm thử timeline xây dựng và tiến độ theo giai đoạn.',
    objectives: 'Bổ sung năng lực nghiên cứu, chỗ ở sinh viên và tiện ích học thuật tại campus Hòa Lạc.',
    currentUpdate: 'Khối nghiên cứu đã cất nóc; ký túc xá đang thi công kết cấu tầng 7 và hệ MEP tầng thấp.',
    risks: 'Nguồn cung thiết bị phòng thí nghiệm có thời gian nhập khẩu dài.',
    nextSteps: 'Hoàn thiện mặt ngoài khối nghiên cứu, chốt danh mục thiết bị và tăng tốc thi công ký túc xá.',
    isFeatured: true,
    isPublic: true,
    sortOrder: 105,
    milestones: [
      ['Khởi công', 'completed', '2025-09-10', '2025-09-10', 100, 'Đúng kế hoạch.'],
      ['Cất nóc khối nghiên cứu', 'completed', '2026-08-31', '2026-08-24', 100, 'Hoàn thành sớm.'],
      ['Hoàn thành phần thô ký túc xá', 'in_progress', '2026-12-31', null, 60, 'Đang thi công.'],
      ['Bàn giao toàn bộ cụm công trình', 'pending', '2027-08-31', null, 0, 'Chờ các giai đoạn tiếp theo.'],
    ],
  },
  {
    code: 'DTHL-PRJ-005',
    slug: 'khu-nha-o-xa-hoi-hoa-lac-binh-yen',
    name: 'Khu nhà ở xã hội Hòa Lạc - Bình Yên',
    shortName: 'NOXH Bình Yên',
    projectType: 'housing',
    status: 'approved',
    priority: 'high',
    progressPercent: 12,
    primaryAreaSlug: 'binh-yen',
    areaSlugs: ['binh-yen', 'hoa-lac'],
    locationText: 'Bình Yên, khu vực Hòa Lạc',
    latitude: 21.031,
    longitude: 105.5074,
    investor: 'Liên danh phát triển nhà ở Hòa Lạc (demo)',
    developer: 'Công ty phát triển nhà ở xã hội HL (demo)',
    managingAuthority: 'Cơ quan quản lý phát triển nhà ở (demo)',
    contractor: 'Chưa lựa chọn nhà thầu xây lắp',
    consultant: 'Tư vấn quy hoạch nhà ở HL (demo)',
    totalInvestmentVnd: 2400000000000,
    fundingSources: ['Vốn doanh nghiệp (demo)', 'Tín dụng dự án (demo)'],
    landAreaHa: 18.5,
    scaleText: 'Khu nhà ở xã hội gồm các khối căn hộ, nhà trẻ, bãi đỗ xe, cây xanh và hạ tầng kỹ thuật nội khu.',
    approvalDecisionNo: 'DEMO/QD-005',
    approvalDecisionDate: '2026-06-12',
    startDate: '2027-01-15',
    expectedCompletionDate: '2029-06-30',
    description: 'Dự án demo phục vụ kiểm thử trạng thái đã phê duyệt, vốn doanh nghiệp và mốc chuẩn bị triển khai.',
    objectives: 'Tạo nguồn cung nhà ở phù hợp cho người lao động, chuyên gia trẻ và lực lượng làm việc tại khu vực Hòa Lạc.',
    currentUpdate: 'Đã hoàn tất phê duyệt dự án; đang chuẩn bị hồ sơ thiết kế kỹ thuật và kế hoạch lựa chọn nhà thầu.',
    risks: 'Phụ thuộc tiến độ hoàn thiện thủ tục đất đai và kết nối hạ tầng ngoài hàng rào.',
    nextSteps: 'Hoàn thiện thiết kế kỹ thuật, thẩm định dự toán và phát hành kế hoạch lựa chọn nhà thầu.',
    isFeatured: false,
    isPublic: true,
    sortOrder: 90,
    milestones: [
      ['Chấp thuận chủ trương đầu tư', 'completed', '2026-04-30', '2026-04-22', 100, 'Đã hoàn tất.'],
      ['Phê duyệt dự án', 'completed', '2026-06-30', '2026-06-12', 100, 'Đã hoàn tất.'],
      ['Hoàn thiện thiết kế kỹ thuật', 'in_progress', '2026-11-30', null, 35, 'Đang triển khai.'],
      ['Khởi công', 'pending', '2027-01-15', null, 0, 'Theo kế hoạch demo.'],
    ],
  },
  {
    code: 'DTHL-PRJ-006',
    slug: 'he-thong-thoat-nuoc-ho-dieu-hoa-hoa-lac',
    name: 'Hệ thống thoát nước và hồ điều hòa Hòa Lạc',
    shortName: 'Thoát nước - hồ điều hòa Hòa Lạc',
    projectType: 'environment',
    status: 'planning',
    priority: 'high',
    progressPercent: 8,
    primaryAreaSlug: 'hoa-lac',
    areaSlugs: ['hoa-lac', 'thach-hoa', 'tan-xa', 'binh-yen'],
    locationText: 'Các lưu vực thoát nước chính khu vực Hòa Lạc',
    latitude: 21.0133,
    longitude: 105.5204,
    investor: 'Ban hạ tầng môi trường Hòa Lạc (demo)',
    developer: 'Đơn vị chuẩn bị dự án môi trường HL (demo)',
    managingAuthority: 'Cơ quan quản lý hạ tầng kỹ thuật (demo)',
    contractor: '',
    consultant: 'Tư vấn thủy lợi - thoát nước Hòa Lạc (demo)',
    totalInvestmentVnd: 1100000000000,
    fundingSources: ['Ngân sách hạ tầng môi trường (demo)'],
    landAreaHa: 36.2,
    scaleText: 'Nạo vét và xây mới tuyến thoát nước chính, hồ điều hòa, trạm bơm cục bộ và hệ thống quan trắc mực nước.',
    approvalDecisionNo: '',
    approvalDecisionDate: null,
    startDate: null,
    expectedCompletionDate: '2029-12-31',
    description: 'Dự án mô phỏng ở giai đoạn lập quy hoạch và chuẩn bị chủ trương, dùng để test các hồ sơ chưa có quyết định phê duyệt.',
    objectives: 'Giảm nguy cơ úng ngập cục bộ, tăng khả năng điều tiết nước mưa và bổ sung không gian mặt nước cảnh quan.',
    currentUpdate: 'Đang khảo sát cao độ, phân chia lưu vực và xây dựng phương án hồ điều hòa ưu tiên.',
    risks: 'Cần đồng bộ với nhiều dự án đường và san nền đang chuẩn bị hoặc triển khai trong khu vực.',
    nextSteps: 'Chốt phương án lưu vực, lập báo cáo tiền khả thi và lấy ý kiến các đơn vị liên quan.',
    isFeatured: false,
    isPublic: true,
    sortOrder: 80,
    milestones: [
      ['Khảo sát hiện trạng thoát nước', 'in_progress', '2026-10-31', null, 70, 'Đang tổng hợp số liệu.'],
      ['Chốt phương án quy hoạch lưu vực', 'pending', '2027-02-28', null, 0, 'Chưa bắt đầu.'],
      ['Trình chủ trương đầu tư', 'pending', '2027-06-30', null, 0, 'Phụ thuộc kết quả quy hoạch.'],
    ],
  },
  {
    code: 'DTHL-PRJ-007',
    slug: 'ha-tang-cum-san-xuat-cong-nghe-ho-tro-ha-bang',
    name: 'Hạ tầng cụm sản xuất công nghệ hỗ trợ Hạ Bằng',
    shortName: 'Cụm công nghệ hỗ trợ Hạ Bằng',
    projectType: 'industrial',
    status: 'preparing',
    priority: 'normal',
    progressPercent: 16,
    primaryAreaSlug: 'ha-bang',
    areaSlugs: ['ha-bang', 'hoa-lac'],
    locationText: 'Hạ Bằng, Thạch Thất, Hà Nội',
    latitude: 21.0405,
    longitude: 105.567,
    investor: 'Công ty phát triển cụm công nghệ Hạ Bằng (demo)',
    developer: 'Đơn vị phát triển hạ tầng công nghiệp HL (demo)',
    managingAuthority: 'Đơn vị quản lý cụm sản xuất (demo)',
    contractor: '',
    consultant: 'Tư vấn hạ tầng công nghiệp Tây Hà Nội (demo)',
    totalInvestmentVnd: 950000000000,
    fundingSources: ['Vốn chủ sở hữu (demo)', 'Vốn tín dụng (demo)'],
    landAreaHa: 42,
    scaleText: 'Hạ tầng đường nội bộ, điện, nước, xử lý nước thải và các lô sản xuất phục vụ doanh nghiệp công nghệ hỗ trợ.',
    approvalDecisionNo: 'DEMO/QD-007',
    approvalDecisionDate: '2026-05-28',
    startDate: '2027-03-01',
    expectedCompletionDate: '2028-12-31',
    description: 'Dữ liệu demo cho dự án công nghiệp ở giai đoạn chuẩn bị đầu tư.',
    objectives: 'Tạo quỹ đất hạ tầng đồng bộ cho doanh nghiệp sản xuất phụ trợ và chuỗi cung ứng công nghệ.',
    currentUpdate: 'Đang hoàn thiện thiết kế cơ sở, kế hoạch giải phóng mặt bằng và hồ sơ môi trường.',
    risks: 'Cần kiểm soát yêu cầu môi trường và kết nối hạ tầng giao thông khu vực.',
    nextSteps: 'Hoàn tất hồ sơ môi trường và thiết kế cơ sở trước khi lập hồ sơ mời thầu.',
    isFeatured: false,
    isPublic: true,
    sortOrder: 70,
    milestones: [
      ['Chấp thuận dự án', 'completed', '2026-06-15', '2026-05-28', 100, 'Đã hoàn tất.'],
      ['Hoàn thiện hồ sơ môi trường', 'in_progress', '2026-12-31', null, 40, 'Đang lấy ý kiến.'],
      ['Phát hành hồ sơ mời thầu hạ tầng', 'pending', '2027-02-15', null, 0, 'Chờ hoàn thiện hồ sơ.'],
    ],
  },
  {
    code: 'DTHL-PRJ-008',
    slug: 'trung-tam-hanh-chinh-dich-vu-cong-hoa-lac',
    name: 'Trung tâm hành chính - dịch vụ công Hòa Lạc',
    shortName: 'Trung tâm dịch vụ công Hòa Lạc',
    projectType: 'public',
    status: 'approved',
    priority: 'normal',
    progressPercent: 10,
    primaryAreaSlug: 'hoa-lac',
    areaSlugs: ['hoa-lac'],
    locationText: 'Khu trung tâm Hòa Lạc',
    latitude: 21.0101,
    longitude: 105.5258,
    investor: 'Ban quản lý công trình công cộng Hòa Lạc (demo)',
    developer: 'Đơn vị phát triển công trình công cộng (demo)',
    managingAuthority: 'Cơ quan quản lý hành chính khu vực (demo)',
    contractor: '',
    consultant: 'Tư vấn kiến trúc công cộng HL (demo)',
    totalInvestmentVnd: 780000000000,
    fundingSources: ['Ngân sách đầu tư công (demo)'],
    landAreaHa: 6.8,
    scaleText: 'Khối tiếp nhận dịch vụ công, không gian làm việc liên thông, hội trường, bãi đỗ xe và quảng trường phía trước.',
    approvalDecisionNo: 'DEMO/QD-008',
    approvalDecisionDate: '2026-07-14',
    startDate: '2027-02-01',
    expectedCompletionDate: '2028-03-31',
    description: 'Dự án demo để kiểm thử nhóm công trình công cộng và dữ liệu pháp lý - đầu tư.',
    objectives: 'Tập trung đầu mối dịch vụ công, tăng khả năng phục vụ người dân và doanh nghiệp trong khu vực.',
    currentUpdate: 'Đã phê duyệt dự án, đang triển khai thiết kế kỹ thuật và dự toán.',
    risks: 'Cần thống nhất yêu cầu vận hành giữa nhiều đơn vị sử dụng công trình.',
    nextSteps: 'Chốt phương án công năng, thẩm định thiết kế kỹ thuật và lập kế hoạch đấu thầu.',
    isFeatured: false,
    isPublic: true,
    sortOrder: 65,
    milestones: [
      ['Phê duyệt dự án', 'completed', '2026-07-31', '2026-07-14', 100, 'Đã hoàn tất.'],
      ['Thiết kế kỹ thuật - dự toán', 'in_progress', '2026-11-30', null, 45, 'Đang triển khai.'],
      ['Lựa chọn nhà thầu', 'pending', '2027-01-20', null, 0, 'Chưa bắt đầu.'],
    ],
  },
  {
    code: 'DTHL-PRJ-009',
    slug: 'nut-giao-dai-lo-thang-long-hoa-lac',
    name: 'Nút giao kết nối Đại lộ Thăng Long - Hòa Lạc',
    shortName: 'Nút giao Đại lộ Thăng Long',
    projectType: 'transport',
    status: 'completed',
    priority: 'high',
    progressPercent: 100,
    primaryAreaSlug: 'dai-lo-thang-long',
    areaSlugs: ['dai-lo-thang-long', 'hoa-lac'],
    locationText: 'Cửa ngõ kết nối Đại lộ Thăng Long vào khu vực Hòa Lạc',
    latitude: 21.0072,
    longitude: 105.5405,
    investor: 'Ban dự án giao thông Hòa Lạc (demo)',
    developer: 'Đơn vị phát triển kết nối giao thông (demo)',
    managingAuthority: 'Đơn vị quản lý giao thông khu vực (demo)',
    contractor: 'Liên danh giao thông HL-09 (demo)',
    consultant: 'Tư vấn giao thông HL (demo)',
    totalInvestmentVnd: 1450000000000,
    fundingSources: ['Ngân sách đầu tư phát triển (demo)'],
    landAreaHa: 14.2,
    lengthKm: 2.1,
    scaleText: 'Nút giao khác mức, đường dẫn, hệ thống chiếu sáng và tổ chức giao thông kết nối khu vực.',
    approvalDecisionNo: 'DEMO/QD-009',
    approvalDecisionDate: '2024-09-10',
    startDate: '2025-01-05',
    expectedCompletionDate: '2026-06-30',
    completedAt: '2026-05-25',
    description: 'Dự án demo đã hoàn thành để kiểm thử trạng thái đóng tiến độ và thống kê completed.',
    objectives: 'Tăng năng lực thông hành tại cửa ngõ và phân luồng phương tiện vào các khu chức năng Hòa Lạc.',
    currentUpdate: 'Công trình đã hoàn thành, nghiệm thu và chuyển sang theo dõi vận hành.',
    risks: '',
    nextSteps: 'Theo dõi vận hành, cập nhật dữ liệu lưu lượng và bảo trì định kỳ.',
    isFeatured: false,
    isPublic: true,
    sortOrder: 60,
    milestones: [
      ['Khởi công', 'completed', '2025-01-05', '2025-01-05', 100, 'Đúng kế hoạch.'],
      ['Thông xe kỹ thuật', 'completed', '2026-04-30', '2026-04-26', 100, 'Hoàn thành sớm.'],
      ['Nghiệm thu và bàn giao', 'completed', '2026-06-30', '2026-05-25', 100, 'Đã bàn giao.'],
    ],
  },
  {
    code: 'DTHL-PRJ-010',
    slug: 'chinh-trang-truc-trung-tam-thach-hoa-tan-xa',
    name: 'Chỉnh trang trục trung tâm Thạch Hòa - Tân Xã',
    shortName: 'Chỉnh trang Thạch Hòa - Tân Xã',
    projectType: 'urban',
    status: 'paused',
    priority: 'normal',
    progressPercent: 37,
    primaryAreaSlug: 'thach-hoa',
    areaSlugs: ['thach-hoa', 'tan-xa', 'hoa-lac'],
    locationText: 'Trục kết nối Thạch Hòa - Tân Xã',
    latitude: 21.022,
    longitude: 105.545,
    investor: 'Ban chỉnh trang đô thị Hòa Lạc (demo)',
    developer: 'Đơn vị phát triển không gian công cộng (demo)',
    managingAuthority: 'Đơn vị quản lý đô thị khu vực (demo)',
    contractor: 'Nhà thầu hạ tầng cảnh quan HL-10 (demo)',
    consultant: 'Tư vấn cảnh quan và giao thông đô thị (demo)',
    totalInvestmentVnd: 520000000000,
    fundingSources: ['Ngân sách hạ tầng đô thị (demo)'],
    lengthKm: 4.8,
    scaleText: 'Cải tạo mặt đường, vỉa hè, cây xanh, chiếu sáng, điểm dừng xe và hệ thống thoát nước dọc tuyến.',
    approvalDecisionNo: 'DEMO/QD-010',
    approvalDecisionDate: '2025-01-18',
    startDate: '2025-06-01',
    expectedCompletionDate: '2026-07-31',
    completedAt: null,
    description: 'Dự án demo cố ý đặt ở trạng thái tạm dừng và quá mốc để kiểm thử cảnh báo chậm tiến độ trên dashboard.',
    objectives: 'Cải thiện an toàn, cảnh quan và chất lượng không gian đi bộ trên trục dân cư hiện hữu.',
    currentUpdate: 'Tạm dừng một số hạng mục để rà soát thiết kế thoát nước và phạm vi giải phóng mặt bằng.',
    risks: 'Đã quá mốc hoàn thành dự kiến; cần điều chỉnh kế hoạch và xử lý xung đột hạ tầng hiện trạng.',
    nextSteps: 'Hoàn tất rà soát thiết kế, cập nhật tổng tiến độ và trình phương án khởi động lại các gói thầu.',
    isFeatured: false,
    isPublic: true,
    sortOrder: 100,
    milestones: [
      ['Cải tạo đoạn 1', 'completed', '2025-12-31', '2026-01-12', 100, 'Hoàn thành chậm.'],
      ['Cải tạo hệ thống thoát nước đoạn 2', 'delayed', '2026-04-30', null, 48, 'Đang tạm dừng để rà soát thiết kế.'],
      ['Hoàn thiện cảnh quan toàn tuyến', 'delayed', '2026-07-31', null, 15, 'Chưa thể hoàn thành theo kế hoạch cũ.'],
    ],
  },
  {
    code: 'DTHL-PRJ-011',
    slug: 'ha-tang-so-do-thi-thong-minh-hoa-lac',
    name: 'Hạ tầng số đô thị thông minh Hòa Lạc',
    shortName: 'Hạ tầng số Hòa Lạc',
    projectType: 'technology',
    status: 'proposed',
    priority: 'high',
    progressPercent: 3,
    primaryAreaSlug: 'hoa-lac',
    areaSlugs: ['hoa-lac', 'khu-do-thi-hoa-lac', 'khu-cong-nghe-cao-hoa-lac'],
    locationText: 'Phạm vi thử nghiệm tại các khu chức năng Hòa Lạc',
    latitude: 21.015,
    longitude: 105.528,
    investor: 'Đơn vị đề xuất nền tảng đô thị số Hòa Lạc (demo)',
    developer: 'Nhóm phát triển dữ liệu đô thị Hòa Lạc (demo)',
    managingAuthority: 'Đơn vị quản lý chuyển đổi số khu vực (demo)',
    contractor: '',
    consultant: 'Tư vấn kiến trúc dữ liệu đô thị (demo)',
    totalInvestmentVnd: 650000000000,
    fundingSources: ['Nguồn vốn chuyển đổi số dự kiến (demo)'],
    scaleText: 'Nền tảng dữ liệu dùng chung, cảm biến IoT, dashboard vận hành, tích hợp bản đồ và các API dữ liệu đô thị.',
    approvalDecisionNo: '',
    approvalDecisionDate: null,
    startDate: null,
    expectedCompletionDate: '2029-06-30',
    description: 'Dự án demo ở giai đoạn đề xuất, được để chế độ nội bộ để test filter visibility trong Project Tracker.',
    objectives: 'Chuẩn hóa dữ liệu vận hành, tạo nền tảng tích hợp cho giao thông, môi trường, hạ tầng và dịch vụ đô thị.',
    currentUpdate: 'Đang xây dựng đề cương kiến trúc dữ liệu và danh mục dịch vụ thí điểm.',
    risks: 'Cần thống nhất chuẩn dữ liệu, quyền truy cập và cơ chế chia sẻ giữa nhiều hệ thống.',
    nextSteps: 'Hoàn thiện đề xuất phạm vi MVP và dự toán sơ bộ trước khi trình chủ trương.',
    isFeatured: false,
    isPublic: false,
    sortOrder: 50,
    milestones: [
      ['Xây dựng đề cương kiến trúc dữ liệu', 'in_progress', '2026-12-31', null, 25, 'Đang thực hiện.'],
      ['Trình đề xuất chủ trương', 'pending', '2027-03-31', null, 0, 'Chờ hoàn thiện đề cương.'],
      ['Thí điểm nền tảng dữ liệu', 'pending', '2027-12-31', null, 0, 'Chưa bắt đầu.'],
    ],
  },
  {
    code: 'DTHL-PRJ-012',
    slug: 'khong-gian-van-hoa-the-thao-cong-dong-yen-xuan',
    name: 'Không gian văn hóa - thể thao cộng đồng Yên Xuân',
    shortName: 'Trung tâm cộng đồng Yên Xuân',
    projectType: 'public',
    status: 'tendering',
    priority: 'low',
    progressPercent: 20,
    primaryAreaSlug: 'yen-xuan',
    areaSlugs: ['yen-xuan', 'hoa-lac'],
    locationText: 'Yên Xuân, khu vực Hòa Lạc',
    latitude: 20.9865,
    longitude: 105.488,
    investor: 'Ban công trình cộng đồng Yên Xuân (demo)',
    developer: 'Đơn vị phát triển tiện ích cộng đồng (demo)',
    managingAuthority: 'Đơn vị quản lý văn hóa - thể thao địa phương (demo)',
    contractor: 'Đang lựa chọn nhà thầu (demo)',
    consultant: 'Tư vấn thiết kế công trình cộng đồng (demo)',
    totalInvestmentVnd: 320000000000,
    fundingSources: ['Ngân sách địa phương (demo)', 'Nguồn xã hội hóa (demo)'],
    landAreaHa: 4.3,
    scaleText: 'Nhà sinh hoạt cộng đồng, sân thể thao đa năng, thư viện nhỏ, sân chơi trẻ em và không gian cây xanh.',
    approvalDecisionNo: 'DEMO/QD-012',
    approvalDecisionDate: '2026-03-30',
    startDate: '2026-11-20',
    expectedCompletionDate: '2027-10-31',
    description: 'Dự án demo quy mô nhỏ để kiểm thử nhóm công trình công cộng và trạng thái đấu thầu.',
    objectives: 'Bổ sung không gian sinh hoạt, thể thao và học tập cộng đồng cho khu vực Yên Xuân.',
    currentUpdate: 'Đang phát hành hồ sơ mời thầu xây lắp và chuẩn bị bàn giao mặt bằng.',
    risks: 'Cần phối hợp lịch thi công để hạn chế ảnh hưởng các hoạt động cộng đồng xung quanh.',
    nextSteps: 'Đóng thầu, đánh giá hồ sơ và ký hợp đồng để khởi công cuối năm 2026.',
    isFeatured: false,
    isPublic: true,
    sortOrder: 45,
    milestones: [
      ['Phê duyệt dự án', 'completed', '2026-04-15', '2026-03-30', 100, 'Đã hoàn tất.'],
      ['Lựa chọn nhà thầu', 'in_progress', '2026-10-31', null, 60, 'Đang đấu thầu.'],
      ['Khởi công', 'pending', '2026-11-20', null, 0, 'Theo kế hoạch.'],
      ['Hoàn thành công trình', 'pending', '2027-10-31', null, 0, 'Chưa bắt đầu.'],
    ],
  },
];

function asDate(value) {
  return value ? new Date(`${value}T00:00:00.000Z`) : null;
}

function buildMilestones(items = []) {
  return items.map(([title, status, targetDate, completedAt, progressPercent, note]) => ({
    title,
    status,
    targetDate: asDate(targetDate),
    completedAt: asDate(completedAt),
    progressPercent,
    note,
  }));
}

function buildUpdates(definition, adminId) {
  const firstDate = definition.startDate || definition.approvalDecisionDate || '2026-01-15';
  return [
    {
      updateDate: asDate(firstDate),
      title: 'Khởi tạo hồ sơ theo dõi dự án',
      summary: 'Tạo dữ liệu theo dõi Project Tracker cho môi trường dev/staging.',
      progressPercent: Math.max(0, Math.min(definition.progressPercent, 10)),
      status: definition.status === 'completed' ? 'construction' : definition.status,
      sourceUrl: `https://example.com/dthl-demo/${definition.slug}/ho-so-ban-dau`,
      createdBy: adminId,
    },
    {
      updateDate: asDate('2026-09-14'),
      title: 'Cập nhật tiến độ gần nhất',
      summary: definition.currentUpdate,
      progressPercent: definition.progressPercent,
      status: definition.status,
      sourceUrl: `https://example.com/dthl-demo/${definition.slug}/cap-nhat`,
      createdBy: adminId,
    },
  ];
}

export async function seedProjectShowcase({ adminUser, areas }) {
  if (!adminUser?._id) throw new Error('Thiếu admin user để seed Project Tracker.');
  if (!areas?.['hoa-lac']) throw new Error('Thiếu taxonomy khu vực để seed Project Tracker.');

  const result = {};

  for (const definition of definitions) {
    const primaryArea = areas[definition.primaryAreaSlug];
    if (!primaryArea) {
      throw new Error(`Không tìm thấy khu vực Project Tracker: ${definition.primaryAreaSlug}`);
    }

    const areaIds = [...new Set(definition.areaSlugs.map((slug) => {
      const area = areas[slug];
      if (!area) throw new Error(`Không tìm thấy khu vực Project Tracker: ${slug}`);
      return String(area._id);
    }))];

    const project = await Project.findOneAndUpdate(
      { code: definition.code },
      {
        $set: {
          code: definition.code,
          name: definition.name,
          shortName: definition.shortName,
          slug: definition.slug,
          projectType: definition.projectType,
          status: definition.status,
          priority: definition.priority,
          progressPercent: definition.progressPercent,
          primaryAreaId: primaryArea._id,
          areaIds,
          locationText: definition.locationText,
          latitude: definition.latitude,
          longitude: definition.longitude,
          investor: definition.investor,
          developer: definition.developer,
          managingAuthority: definition.managingAuthority,
          contractor: definition.contractor,
          consultant: definition.consultant,
          totalInvestmentVnd: definition.totalInvestmentVnd,
          fundingSources: definition.fundingSources,
          landAreaHa: definition.landAreaHa ?? null,
          lengthKm: definition.lengthKm ?? null,
          scaleText: definition.scaleText,
          approvalDecisionNo: definition.approvalDecisionNo,
          approvalDecisionDate: asDate(definition.approvalDecisionDate),
          startDate: asDate(definition.startDate),
          expectedCompletionDate: asDate(definition.expectedCompletionDate),
          completedAt: asDate(definition.completedAt),
          description: definition.description,
          objectives: definition.objectives,
          currentUpdate: definition.currentUpdate,
          risks: definition.risks,
          nextSteps: definition.nextSteps,
          milestones: buildMilestones(definition.milestones),
          updates: buildUpdates(definition, adminUser._id),
          sourceUrls: [
            {
              label: 'Nguồn minh họa - dữ liệu seed demo',
              url: `https://example.com/dthl-demo/${definition.slug}`,
            },
          ],
          isFeatured: definition.isFeatured,
          isPublic: definition.isPublic,
          sortOrder: definition.sortOrder,
          createdBy: adminUser._id,
          updatedBy: adminUser._id,
          deletedAt: null,
        },
      },
      {
        upsert: true,
        new: true,
        runValidators: true,
        setDefaultsOnInsert: true,
      },
    );

    result[definition.code] = project;
  }

  return result;
}

export { definitions as projectShowcaseDefinitions };
