import PropertyListing from '../modules/properties/propertyListing.model.js';
import PropertyPriceHistory from '../modules/properties/propertyPriceHistory.model.js';
import { makeBody, upsertContent, daysFromSeed } from './seedHelpers.js';

const definitions = [
  {
    slug: 'ban-dat-thach-hoa-120m2-duong-o-to',
    title: 'Bán đất Thạch Hòa 120 m², đường ô tô',
    transactionType: 'sale',
    propertyType: 'residential_land',
    ownerType: 'owner',
    price: 3600000000,
    landArea: 120,
    area: 'thach-hoa',
    category: 'mua-ban-nha-dat',
    media: 'property-land',
    legalStatus: 'red_book',
    features: ['o-to-vao-tan-noi', 'co-so-do', 'co-the-xay-dung-ngay'],
    author: 'resident',
    address: 'Thạch Hòa, Hòa Lạc',
  },
  {
    slug: 'ban-dat-nen-binh-yen-100m2',
    title: 'Bán đất nền Bình Yên 100 m² gần Đại lộ Thăng Long',
    transactionType: 'sale',
    propertyType: 'land_plot',
    ownerType: 'broker',
    price: 2850000000,
    landArea: 100,
    area: 'binh-yen',
    category: 'mua-ban-nha-dat',
    media: 'property-land',
    legalStatus: 'red_book',
    features: ['gan-dai-lo-thang-long', 'co-so-do'],
    author: 'broker',
    address: 'Bình Yên, Thạch Thất',
  },
  {
    slug: 'cho-thue-nha-nguyen-can-tan-xa',
    title: 'Cho thuê nhà nguyên căn tại Tân Xã',
    transactionType: 'rent',
    propertyType: 'whole_house',
    ownerType: 'owner',
    price: 12000000,
    priceUnit: 'per_month',
    landArea: 85,
    usableArea: 150,
    bedrooms: 4,
    bathrooms: 3,
    area: 'tan-xa',
    category: 'cho-thue',
    media: 'property-house',
    legalStatus: 'contract',
    features: ['dien-nuoc-day-du', 'phu-hop-o-lau-dai'],
    author: 'resident',
    address: 'Tân Xã, Hòa Lạc',
  },
  {
    slug: 'phong-tro-gan-dai-hoc-quoc-gia',
    title: 'Phòng trọ gần Đại học Quốc gia, đầy đủ nội thất',
    transactionType: 'rent',
    propertyType: 'room',
    ownerType: 'business',
    price: 2800000,
    priceUnit: 'per_month',
    landArea: 25,
    usableArea: 25,
    bedrooms: 1,
    bathrooms: 1,
    area: 'dai-hoc-quoc-gia-ha-noi',
    category: 'cho-thue',
    media: 'property-room',
    legalStatus: 'contract',
    features: ['gan-dai-hoc-quoc-gia', 'dien-nuoc-day-du'],
    author: 'business',
    address: 'Khu vực Đại học Quốc gia Hà Nội',
  },
  {
    slug: 'can-mua-dat-hoa-lac-tu-80-den-120m2',
    title: 'Cần mua đất Hòa Lạc từ 80 đến 120 m²',
    transactionType: 'wanted_buy',
    propertyType: 'residential_land',
    ownerType: 'owner',
    price: 3000000000,
    landArea: 80,
    area: 'hoa-lac',
    category: 'can-mua-can-thue',
    media: 'property-land',
    legalStatus: 'unknown',
    features: ['o-to-vao-tan-noi'],
    author: 'member',
    address: 'Khu vực Hòa Lạc',
  },
  {
    slug: 'sang-nhuong-mat-bang-kinh-doanh-thach-hoa',
    title: 'Sang nhượng mặt bằng kinh doanh tại Thạch Hòa',
    transactionType: 'transfer',
    propertyType: 'commercial_space',
    ownerType: 'business',
    price: 450000000,
    landArea: 90,
    usableArea: 120,
    area: 'thach-hoa',
    category: 'sang-nhuong',
    media: 'property-house',
    legalStatus: 'contract',
    features: ['phu-hop-kinh-doanh', 'o-to-vao-tan-noi'],
    author: 'business',
    address: 'Trục đường chính Thạch Hòa',
  },
  {
    slug: 'ban-nha-vuon-tien-xuan-phu-hop-homestay',
    title: 'Bán nhà vườn Tiến Xuân phù hợp làm homestay',
    transactionType: 'sale',
    propertyType: 'farm',
    ownerType: 'broker',
    price: 7800000000,
    landArea: 650,
    usableArea: 220,
    bedrooms: 5,
    bathrooms: 5,
    area: 'tien-xuan',
    category: 'mua-ban-nha-dat',
    media: 'property-house',
    legalStatus: 'red_book',
    features: ['phu-hop-lam-homestay', 'o-to-vao-tan-noi', 'co-so-do'],
    author: 'broker',
    address: 'Tiến Xuân, Thạch Thất',
  },
  {
    slug: 'cho-thue-van-phong-khu-cong-nghe-cao',
    title: 'Cho thuê văn phòng gần Khu Công nghệ cao',
    transactionType: 'rent',
    propertyType: 'office',
    ownerType: 'business',
    price: 25000000,
    priceUnit: 'per_month',
    landArea: 140,
    usableArea: 140,
    area: 'khu-cong-nghe-cao-hoa-lac',
    category: 'cho-thue',
    media: 'property-house',
    legalStatus: 'contract',
    features: ['gan-khu-cong-nghe-cao', 'dien-nuoc-day-du', 'phu-hop-kinh-doanh'],
    author: 'business',
    address: 'Khu Công nghệ cao Hòa Lạc',
  },

  // Ba tin mẫu thuộc tài khoản admin, ở trạng thái chờ duyệt.
  {
    slug: 'tin-mau-ban-dat-yen-binh-120m2',
    title: '[TIN MẪU] Bán lô đất 120 m² tại Yên Bình, đường ô tô vào tận nơi',
    summary:
      'Tin mẫu phục vụ kiểm thử. Lô đất vuông vắn, mặt tiền rộng, đường ô tô tiếp cận thuận tiện và gần khu dân cư hiện hữu.',
    bodyHtml: makeBody('[TIN MẪU] Bán lô đất 120 m² tại Yên Bình', [
      'Đây là dữ liệu mẫu phục vụ kiểm thử hệ thống, không phải tin giao dịch thực tế.',
      'Lô đất có diện tích 120 m², mặt tiền 6 m, đường vào khoảng 5 m và phù hợp xây nhà ở lâu dài.',
      'Người xem cần kiểm tra quy hoạch, pháp lý và hiện trạng trước khi quyết định giao dịch.',
    ]),
    transactionType: 'sale',
    propertyType: 'residential_land',
    ownerType: 'owner',
    price: 3200000000,
    priceUnit: 'total',
    isNegotiable: true,
    landArea: 120,
    frontage: 6,
    roadWidth: 5,
    direction: 'southeast',
    area: 'yen-binh',
    category: 'mua-ban-nha-dat',
    media: 'property-land',
    legalStatus: 'red_book',
    features: ['o-to-vao-tan-noi', 'co-so-do', 'co-the-xay-dung-ngay'],
    author: 'admin',
    address: 'Khu vực Yên Bình, huyện Thạch Thất, Hà Nội',
    status: 'pending_review',
  },
  {
    slug: 'tin-mau-cho-thue-nha-3-tang-thach-hoa',
    title: '[TIN MẪU] Cho thuê nhà 3 tầng tại Thạch Hòa, gần Đại học Quốc gia Hà Nội',
    summary:
      'Tin mẫu kiểm thử. Nhà 3 tầng có 4 phòng ngủ, không gian rộng rãi, đường ô tô thuận tiện, phù hợp gia đình hoặc nhóm chuyên gia.',
    bodyHtml: makeBody('[TIN MẪU] Cho thuê nhà 3 tầng tại Thạch Hòa', [
      'Đây là dữ liệu mẫu phục vụ kiểm thử hệ thống, không phải tin cho thuê thực tế.',
      'Nhà được xây dựng 3 tầng trên khu đất khoảng 90 m², tổng diện tích sử dụng khoảng 220 m².',
      'Công năng gồm 4 phòng ngủ, 3 phòng tắm, phòng khách, bếp và khu vực để xe.',
    ]),
    transactionType: 'rent',
    propertyType: 'whole_house',
    ownerType: 'owner',
    price: 12000000,
    priceUnit: 'per_month',
    isNegotiable: true,
    landArea: 90,
    usableArea: 220,
    bedrooms: 4,
    bathrooms: 3,
    frontage: 5,
    roadWidth: 6,
    direction: 'south',
    area: 'thach-hoa',
    category: 'cho-thue',
    media: 'property-house',
    legalStatus: 'red_book',
    features: ['o-to-vao-tan-noi', 'dien-nuoc-day-du', 'phu-hop-o-lau-dai'],
    author: 'admin',
    address: 'Khu vực Thạch Hòa, huyện Thạch Thất, Hà Nội',
    status: 'pending_review',
  },
  {
    slug: 'tin-mau-ban-biet-thu-nghi-duong-tien-xuan',
    title: '[TIN MẪU] Bán biệt thự nghỉ dưỡng 350 m² tại Tiến Xuân, không gian xanh',
    summary:
      'Tin mẫu kiểm thử. Biệt thự nghỉ dưỡng có khuôn viên rộng, nhiều cây xanh, 5 phòng ngủ và đường ô tô tiếp cận thuận tiện.',
    bodyHtml: makeBody('[TIN MẪU] Bán biệt thự nghỉ dưỡng tại Tiến Xuân', [
      'Đây là dữ liệu mẫu phục vụ kiểm thử hệ thống, không phải tin bán thực tế.',
      'Biệt thự nằm trên khu đất khoảng 350 m², diện tích sử dụng khoảng 280 m², có 5 phòng ngủ và 6 phòng tắm.',
      'Không gian phù hợp nghỉ dưỡng gia đình hoặc khai thác lưu trú cuối tuần.',
    ]),
    transactionType: 'sale',
    propertyType: 'villa',
    ownerType: 'owner',
    price: 8900000000,
    priceUnit: 'total',
    isNegotiable: true,
    landArea: 350,
    usableArea: 280,
    bedrooms: 5,
    bathrooms: 6,
    frontage: 15,
    roadWidth: 8,
    direction: 'northwest',
    area: 'tien-xuan',
    category: 'mua-ban-nha-dat',
    media: 'property-house',
    legalStatus: 'red_book',
    features: ['phu-hop-lam-homestay', 'o-to-vao-tan-noi', 'co-so-do'],
    author: 'admin',
    address: 'Khu vực Tiến Xuân, huyện Thạch Thất, Hà Nội',
    status: 'pending_review',
  },
];

export async function seedProperties({ users, categories, areas, tags, media, propertyFeatures }) {
  const result = {};

  for (let index = 0; index < definitions.length; index += 1) {
    const item = definitions[index];
    const status = item.status || 'published';
    const content = await upsertContent({
      slug: item.slug,
      contentType: 'property',
      authorId: users[item.author]._id,
      title: item.title,
      summary:
        item.summary ||
        `${item.title}. Tin mẫu có cấu trúc để kiểm thử bộ lọc và trang chi tiết bất động sản.`,
      bodyHtml:
        item.bodyHtml ||
        makeBody(item.title, [
          'Thông tin mô tả được tạo cho môi trường phát triển và không phải tin giao dịch thật.',
          'Người xem cần kiểm tra pháp lý, vị trí và hiện trạng trước khi quyết định.',
        ]),
      thumbnailMediaId: media[item.media]._id,
      primaryCategoryId: categories[`property:${item.category}`]._id,
      primaryAreaId: areas[item.area]._id,
      categoryIds: [categories[`property:${item.category}`]._id],
      areaIds: [areas[item.area]._id, areas['hoa-lac']._id],
      tagIds: [tags['gia-dat']._id, tags['hoa-lac']._id],
      status,
      publishedAt: status === 'published' ? daysFromSeed(-index - 1) : null,
      viewCount: status === 'published' ? 300 + index * 90 : 0,
    });

    const featureIds = item.features.map((slug) => propertyFeatures[slug]?._id).filter(Boolean);
    const listing = await PropertyListing.findOneAndUpdate(
      { contentId: content._id },
      {
        $set: {
          transactionType: item.transactionType,
          propertyType: item.propertyType,
          ownerType: item.ownerType,
          price: item.price,
          priceUnit: item.priceUnit || 'total',
          isNegotiable: item.isNegotiable ?? item.priceUnit === 'negotiable',
          landArea: item.landArea,
          usableArea: item.usableArea ?? null,
          bedrooms: item.bedrooms ?? null,
          bathrooms: item.bathrooms ?? null,
          frontage: item.frontage ?? 5 + (index % 4),
          roadWidth: item.roadWidth ?? 4 + (index % 5),
          direction: item.direction || ['east', 'southeast', 'south', 'unknown'][index % 4],
          legalStatus: item.legalStatus,
          addressText: item.address,
          contactName: users[item.author].displayName,
          contactPhone: users[item.author].phone || '0966709790',
          contactEmail: users[item.author].email,
          featureIds,
          expiresAt: daysFromSeed(30 - index),
          soldAt: null,
          rentedAt: null,
        },
      },
      { upsert: true, new: true, runValidators: true, setDefaultsOnInsert: true },
    );

    if (status === 'published') {
      await PropertyPriceHistory.findOneAndUpdate(
        { contentId: content._id, changedAt: daysFromSeed(-index - 2) },
        {
          $set: {
            oldPrice: Math.round(item.price * 1.05),
            newPrice: item.price,
            changedBy: users[item.author]._id,
          },
        },
        { upsert: true, new: true, setDefaultsOnInsert: true },
      );
    }

    result[item.slug] = { content, listing };
  }

  const expiredContent = await upsertContent({
    slug: 'tin-bat-dong-san-da-het-han',
    contentType: 'property',
    authorId: users.broker._id,
    title: 'Tin bất động sản đã hết hạn',
    summary: 'Dữ liệu mẫu để kiểm thử trạng thái hết hạn.',
    bodyHtml: makeBody('Tin bất động sản đã hết hạn'),
    primaryCategoryId: categories['property:mua-ban-nha-dat']._id,
    primaryAreaId: areas['hoa-lac']._id,
    thumbnailMediaId: media['property-land']._id,
    status: 'expired',
  });

  await PropertyListing.findOneAndUpdate(
    { contentId: expiredContent._id },
    {
      $set: {
        transactionType: 'sale',
        propertyType: 'land_plot',
        ownerType: 'broker',
        price: 2000000000,
        priceUnit: 'total',
        landArea: 90,
        legalStatus: 'red_book',
        addressText: 'Hòa Lạc',
        contactName: users.broker.displayName,
        contactPhone: users.broker.phone,
        contactEmail: users.broker.email,
        featureIds: [],
        expiresAt: daysFromSeed(-1),
      },
    },
    { upsert: true, new: true, runValidators: true },
  );

  result[expiredContent.slug] = { content: expiredContent };

  return result;
}
