import JobPost from '../modules/jobs/jobPost.model.js';
import { upsertContent } from './seedHelpers.js';

// 15 tin tuyển dụng mẫu dùng để kiểm thử giao diện/API dev-staging.
// Doanh nghiệp và thông tin liên hệ trong seed là dữ liệu mô phỏng.
const definitions = [
  {
    slug: 'ai-engineer-khu-cong-nghe-cao-hoa-lac',
    title: 'AI Engineer - Khu Công nghệ cao Hòa Lạc',
    summary: 'Tuyển AI Engineer phát triển pipeline dữ liệu, mô hình machine learning và dịch vụ suy luận cho nền tảng công nghệ tại Hòa Lạc.',
    jobType: 'full_time',
    categorySlug: 'viec-lam-cong-nghe-cao',
    areaSlug: 'khu-cong-nghe-cao-hoa-lac',
    companyName: 'Công ty Công nghệ Hòa Lạc Digital',
    salaryMin: 28000000,
    salaryMax: 45000000,
    salaryUnit: 'month',
    experienceLevel: '1_3_years',
    positionsCount: 3,
    deadlineDays: 40,
    mediaKey: 'job-tech',
    workLocation: 'Khu Công nghệ cao Hòa Lạc, Thạch Thất, Hà Nội',
    schedule: 'Thứ Hai - Thứ Sáu, 08:30 - 17:30; làm việc tại văn phòng, linh hoạt 1 ngày/tuần sau thử việc.',
    responsibilities: [
      'Xây dựng pipeline tiền xử lý dữ liệu, huấn luyện và đánh giá mô hình machine learning.',
      'Triển khai API inference, theo dõi chất lượng mô hình và tối ưu hiệu năng.',
      'Phối hợp cùng backend và product để đưa tính năng AI vào sản phẩm.',
      'Viết tài liệu kỹ thuật, thử nghiệm và báo cáo kết quả theo sprint.',
    ],
    requirements: [
      'Có từ 1 năm kinh nghiệm Python và machine learning ứng dụng.',
      'Sử dụng được pandas, scikit-learn; biết PyTorch hoặc TensorFlow là lợi thế.',
      'Hiểu REST API, Git, Docker và quy trình triển khai dịch vụ.',
      'Có khả năng đọc tài liệu tiếng Anh và trình bày kết quả rõ ràng.',
    ],
    benefits: [
      'Lương 28 - 45 triệu đồng/tháng theo năng lực.',
      'Thưởng hiệu quả dự án và xét tăng lương định kỳ.',
      'Ngân sách học tập, khóa học và chứng chỉ chuyên môn.',
      'BHXH, ngày phép và thiết bị làm việc theo chính sách công ty.',
    ],
  },
  {
    slug: 'frontend-react-developer-hoa-lac',
    title: 'Frontend React Developer - Hòa Lạc',
    summary: 'Tuyển Frontend Developer xây dựng giao diện web bằng React, tối ưu trải nghiệm người dùng và phối hợp phát triển sản phẩm số.',
    jobType: 'full_time',
    categorySlug: 'viec-lam-cong-nghe-cao',
    areaSlug: 'hoa-lac',
    companyName: 'Công ty CP Nền tảng Số Hòa Lạc',
    salaryMin: 18000000,
    salaryMax: 30000000,
    salaryUnit: 'month',
    experienceLevel: '1_3_years',
    positionsCount: 2,
    deadlineDays: 35,
    mediaKey: 'job-tech',
    workLocation: 'Trung tâm Hòa Lạc, Hà Nội',
    schedule: 'Thứ Hai - Thứ Sáu, 08:30 - 17:30.',
    responsibilities: [
      'Phát triển giao diện React theo thiết kế và yêu cầu nghiệp vụ.',
      'Tích hợp REST API, quản lý state và xử lý trạng thái loading/error.',
      'Tối ưu responsive, accessibility và hiệu năng tải trang.',
      'Review code và phối hợp với backend, QA trong chu kỳ release.',
    ],
    requirements: [
      'Có kinh nghiệm React và JavaScript/TypeScript thực tế.',
      'Nắm HTML, CSS, responsive và Git.',
      'Biết Vite, testing frontend hoặc CI/CD là lợi thế.',
      'Có tư duy sản phẩm và chú ý chi tiết giao diện.',
    ],
    benefits: [
      'Lương 18 - 30 triệu đồng/tháng.',
      'Thưởng sprint và thưởng hiệu quả cuối năm.',
      'Trang thiết bị làm việc, phụ cấp ăn trưa.',
      'Được tham gia sản phẩm từ giai đoạn thiết kế tới vận hành.',
    ],
  },
  {
    slug: 'qa-automation-engineer-khu-cnc-hoa-lac',
    title: 'QA Automation Engineer - Khu CNC Hòa Lạc',
    summary: 'Tuyển QA Automation xây dựng bộ kiểm thử API/UI, kiểm soát regression và hỗ trợ nâng cao chất lượng phát hành phần mềm.',
    jobType: 'full_time',
    categorySlug: 'viec-lam-cong-nghe-cao',
    areaSlug: 'khu-cong-nghe-cao-hoa-lac',
    companyName: 'HLS Software Lab',
    salaryMin: 20000000,
    salaryMax: 32000000,
    salaryUnit: 'month',
    experienceLevel: '1_3_years',
    positionsCount: 2,
    deadlineDays: 33,
    mediaKey: 'job-tech',
    workLocation: 'Khu Công nghệ cao Hòa Lạc, Hà Nội',
    schedule: 'Thứ Hai - Thứ Sáu, 08:30 - 17:30.',
    responsibilities: [
      'Thiết kế test case cho web/API và duy trì bộ regression.',
      'Viết automation test bằng Playwright, Cypress hoặc công cụ tương đương.',
      'Theo dõi bug, phối hợp developer xác minh nguyên nhân và mức độ ảnh hưởng.',
      'Đưa automation vào pipeline CI và báo cáo chất lượng release.',
    ],
    requirements: [
      'Có kinh nghiệm kiểm thử phần mềm và ít nhất một framework automation.',
      'Hiểu HTTP, REST API, database cơ bản và Git.',
      'Có khả năng phân tích lỗi và viết tài liệu test rõ ràng.',
      'Biết JavaScript/TypeScript hoặc Python là lợi thế.',
    ],
    benefits: [
      'Lương 20 - 32 triệu đồng/tháng.',
      'Thưởng release và đánh giá năng lực định kỳ.',
      'Được đào tạo thêm automation, performance và security testing.',
      'Bảo hiểm và phúc lợi theo chính sách công ty.',
    ],
  },
  {
    slug: 'thuc-tap-sinh-iot-embedded-hoa-lac',
    title: 'Thực tập sinh IoT / Embedded - Hòa Lạc',
    summary: 'Cơ hội thực tập cho sinh viên điện tử, tự động hóa và CNTT tham gia thử nghiệm thiết bị IoT, firmware và hệ thống cảm biến.',
    jobType: 'internship',
    categorySlug: 'viec-lam-sinh-vien',
    areaSlug: 'khu-cong-nghe-cao-hoa-lac',
    companyName: 'Hòa Lạc IoT Lab',
    salaryMin: 4500000,
    salaryMax: 7500000,
    salaryUnit: 'month',
    experienceLevel: 'none',
    positionsCount: 5,
    deadlineDays: 28,
    mediaKey: 'job-tech',
    workLocation: 'Khu Công nghệ cao Hòa Lạc, Hà Nội',
    schedule: 'Tối thiểu 4 ngày/tuần, linh hoạt theo lịch học.',
    responsibilities: [
      'Hỗ trợ lắp ráp, kiểm tra bo mạch và thiết bị cảm biến.',
      'Viết firmware mẫu cho ESP32/STM32 theo hướng dẫn của mentor.',
      'Ghi nhận dữ liệu thử nghiệm và cập nhật tài liệu kỹ thuật.',
      'Hỗ trợ demo prototype và kiểm thử kết nối thiết bị.',
    ],
    requirements: [
      'Sinh viên năm 3, năm cuối hoặc mới tốt nghiệp ngành phù hợp.',
      'Biết C/C++ cơ bản; từng dùng Arduino/ESP32 là lợi thế.',
      'Có tư duy thực hành và tuân thủ quy trình phòng lab.',
      'Có thể tham gia tối thiểu 3 tháng.',
    ],
    benefits: [
      'Hỗ trợ 4,5 - 7,5 triệu đồng/tháng.',
      'Có mentor kỹ thuật và lộ trình thực tập rõ ràng.',
      'Được sử dụng thiết bị lab và tham gia prototype thực tế.',
      'Có cơ hội chuyển chính thức sau kỳ thực tập.',
    ],
  },
  {
    slug: 'ky-su-giam-sat-xay-dung-thach-hoa',
    title: 'Kỹ sư giám sát xây dựng - Thạch Hòa',
    summary: 'Tuyển kỹ sư giám sát công trình dân dụng tại Thạch Hòa, theo dõi chất lượng, tiến độ, vật tư và hồ sơ nghiệm thu.',
    jobType: 'construction',
    categorySlug: 'viec-lam-xay-dung',
    areaSlug: 'thach-hoa',
    companyName: 'Công ty Xây dựng Hòa Lạc Build',
    salaryMin: 16000000,
    salaryMax: 24000000,
    salaryUnit: 'month',
    experienceLevel: '1_3_years',
    positionsCount: 3,
    deadlineDays: 36,
    mediaKey: 'article-construction',
    workLocation: 'Thạch Hòa, Thạch Thất, Hà Nội',
    schedule: 'Thứ Hai - Thứ Bảy; thời gian theo tiến độ công trường.',
    responsibilities: [
      'Giám sát thi công phần thô, hoàn thiện và hạ tầng kỹ thuật.',
      'Kiểm tra vật liệu, biện pháp thi công và chất lượng hạng mục.',
      'Lập nhật ký, hồ sơ nghiệm thu và báo cáo tiến độ.',
      'Phối hợp chủ đầu tư, nhà thầu phụ và đội thi công xử lý phát sinh.',
    ],
    requirements: [
      'Tốt nghiệp Xây dựng dân dụng hoặc ngành liên quan.',
      'Có 1 - 3 năm kinh nghiệm giám sát công trình.',
      'Đọc bản vẽ tốt, sử dụng AutoCAD và Excel.',
      'Chủ động, trung thực và chịu được môi trường công trường.',
    ],
    benefits: [
      'Lương 16 - 24 triệu đồng/tháng.',
      'Phụ cấp công trường, điện thoại và ăn trưa.',
      'Thưởng theo tiến độ và chất lượng dự án.',
      'Được tham gia các dự án nhà ở và công trình dịch vụ tại Hòa Lạc.',
    ],
  },
  {
    slug: 'kien-truc-su-thiet-ke-nha-o-hoa-lac',
    title: 'Kiến trúc sư thiết kế nhà ở - Hòa Lạc',
    summary: 'Tuyển kiến trúc sư triển khai ý tưởng, hồ sơ thiết kế và phối cảnh cho nhà ở, villa và công trình dịch vụ tại khu vực Hòa Lạc.',
    jobType: 'full_time',
    categorySlug: 'viec-lam-xay-dung',
    areaSlug: 'hoa-lac',
    companyName: 'Hòa Lạc Architecture Studio',
    salaryMin: 15000000,
    salaryMax: 26000000,
    salaryUnit: 'month',
    experienceLevel: '1_3_years',
    positionsCount: 2,
    deadlineDays: 34,
    mediaKey: 'article-construction',
    workLocation: 'Hòa Lạc, Hà Nội',
    schedule: 'Thứ Hai - Thứ Sáu và sáng Thứ Bảy cách tuần.',
    responsibilities: [
      'Phát triển concept kiến trúc và bố trí mặt bằng theo brief khách hàng.',
      'Triển khai hồ sơ thiết kế cơ sở, phối cảnh và bản vẽ chi tiết.',
      'Phối hợp kết cấu, MEP và nội thất để kiểm soát xung đột.',
      'Tham gia trao đổi khách hàng và hỗ trợ tác giả tại công trường.',
    ],
    requirements: [
      'Tốt nghiệp Kiến trúc hoặc ngành liên quan.',
      'Sử dụng AutoCAD và một công cụ 3D/render phù hợp.',
      'Có portfolio nhà ở hoặc công trình dân dụng.',
      'Có khả năng trình bày ý tưởng và quản lý deadline.',
    ],
    benefits: [
      'Lương 15 - 26 triệu đồng/tháng.',
      'Thưởng theo dự án và chất lượng hồ sơ.',
      'Được tham gia dự án thực tế từ concept đến thi công.',
      'Hỗ trợ phần mềm, máy trạm và đào tạo chuyên môn.',
    ],
  },
  {
    slug: 'ky-su-qs-du-toan-ha-bang',
    title: 'Kỹ sư QS / Dự toán - Hạ Bằng',
    summary: 'Tuyển kỹ sư QS bóc tách khối lượng, lập dự toán, theo dõi phát sinh và hồ sơ thanh quyết toán công trình.',
    jobType: 'construction',
    categorySlug: 'viec-lam-xay-dung',
    areaSlug: 'ha-bang',
    companyName: 'Công ty CP Xây dựng Tây Hà Nội',
    salaryMin: 17000000,
    salaryMax: 26000000,
    salaryUnit: 'month',
    experienceLevel: '1_3_years',
    positionsCount: 2,
    deadlineDays: 37,
    mediaKey: 'article-construction',
    workLocation: 'Hạ Bằng, Thạch Thất, Hà Nội',
    schedule: 'Thứ Hai - Thứ Sáu và sáng Thứ Bảy.',
    responsibilities: [
      'Bóc tách khối lượng và lập dự toán theo hồ sơ thiết kế.',
      'Theo dõi hợp đồng, phát sinh và khối lượng nghiệm thu.',
      'Kiểm tra hồ sơ thanh toán của thầu phụ và nhà cung cấp.',
      'Cập nhật ngân sách và báo cáo chi phí dự án.',
    ],
    requirements: [
      'Tốt nghiệp Kinh tế xây dựng, Xây dựng hoặc ngành liên quan.',
      'Có kinh nghiệm QS/dự toán từ 1 năm.',
      'Sử dụng tốt Excel và phần mềm dự toán.',
      'Cẩn thận với số liệu, hợp đồng và hồ sơ.',
    ],
    benefits: [
      'Lương 17 - 26 triệu đồng/tháng.',
      'Thưởng dự án và phụ cấp công tác.',
      'Được đào tạo thêm về hợp đồng và quản trị chi phí.',
      'BHXH và ngày phép theo quy định.',
    ],
  },
  {
    slug: 'le-tan-khu-nghi-duong-tien-xuan',
    title: 'Nhân viên lễ tân khu nghỉ dưỡng - Tiến Xuân',
    summary: 'Tuyển lễ tân đón tiếp khách, quản lý booking, hỗ trợ check-in/check-out và phối hợp dịch vụ tại khu nghỉ dưỡng Tiến Xuân.',
    jobType: 'service',
    categorySlug: 'viec-lam-dich-vu',
    areaSlug: 'tien-xuan',
    companyName: 'Tiến Xuân Garden Retreat',
    salaryMin: 9000000,
    salaryMax: 13000000,
    salaryUnit: 'month',
    experienceLevel: 'none',
    positionsCount: 4,
    deadlineDays: 30,
    mediaKey: 'job-service',
    workLocation: 'Tiến Xuân, khu vực Hòa Lạc, Hà Nội',
    schedule: 'Làm theo ca 8 giờ, có ca cuối tuần và ngày lễ.',
    responsibilities: [
      'Đón khách, thực hiện check-in/check-out và hướng dẫn tiện ích.',
      'Tiếp nhận booking, cập nhật trạng thái phòng và thông tin khách.',
      'Phối hợp buồng phòng, bếp và kỹ thuật xử lý yêu cầu.',
      'Ghi nhận phản hồi và bàn giao đầy đủ giữa các ca.',
    ],
    requirements: [
      'Tốt nghiệp THPT trở lên; không bắt buộc kinh nghiệm.',
      'Giao tiếp lịch sự, tác phong gọn gàng và chủ động.',
      'Sử dụng máy tính, email và ứng dụng văn phòng cơ bản.',
      'Có thể làm ca và cuối tuần.',
    ],
    benefits: [
      'Lương 9 - 13 triệu đồng/tháng.',
      'Phụ cấp ca, bữa ăn và thưởng dịch vụ.',
      'Được đào tạo nghiệp vụ lễ tân và chăm sóc khách hàng.',
      'Có lộ trình lên ca trưởng hoặc giám sát.',
    ],
  },
  {
    slug: 'quan-ly-van-hanh-homestay-yen-xuan',
    title: 'Quản lý vận hành homestay - Yên Xuân',
    summary: 'Tuyển quản lý vận hành homestay phụ trách lịch phòng, nhân sự ca, chất lượng dịch vụ và trải nghiệm khách hàng.',
    jobType: 'full_time',
    categorySlug: 'viec-lam-dich-vu',
    areaSlug: 'yen-xuan',
    companyName: 'Yên Xuân Hills Stay',
    salaryMin: 15000000,
    salaryMax: 22000000,
    salaryUnit: 'month',
    experienceLevel: '1_3_years',
    positionsCount: 1,
    deadlineDays: 32,
    mediaKey: 'job-service',
    workLocation: 'Yên Xuân, Thạch Thất, Hà Nội',
    schedule: 'Làm việc theo lịch vận hành; nghỉ luân phiên 1 ngày/tuần.',
    responsibilities: [
      'Điều phối booking, tình trạng phòng và kế hoạch đón khách.',
      'Sắp xếp nhân sự ca, kiểm tra checklist vệ sinh và bảo trì.',
      'Theo dõi đánh giá khách hàng và xử lý khiếu nại.',
      'Kiểm soát vật tư tiêu hao và báo cáo doanh thu vận hành cơ bản.',
    ],
    requirements: [
      'Có kinh nghiệm lưu trú, khách sạn hoặc homestay từ 1 năm.',
      'Có khả năng điều phối nhóm nhỏ và xử lý tình huống.',
      'Sử dụng tốt bảng tính và nền tảng booking.',
      'Có thể làm cuối tuần và ngày lễ theo lịch.',
    ],
    benefits: [
      'Lương 15 - 22 triệu đồng/tháng.',
      'Thưởng theo doanh thu và đánh giá khách hàng.',
      'Hỗ trợ bữa ăn và chỗ nghỉ trong ca muộn khi cần.',
      'Có quyền chủ động cải tiến quy trình vận hành.',
    ],
  },
  {
    slug: 'barista-ban-thoi-gian-khu-do-thi-hoa-lac',
    title: 'Barista bán thời gian - Khu đô thị Hòa Lạc',
    summary: 'Việc làm bán thời gian pha chế đồ uống, phục vụ khách và hỗ trợ vận hành quầy cà phê, phù hợp sinh viên và người cần lịch linh hoạt.',
    jobType: 'part_time',
    categorySlug: 'viec-lam-sinh-vien',
    areaSlug: 'khu-do-thi-hoa-lac',
    companyName: 'Hòa Lạc Corner Coffee',
    salaryMin: 28000,
    salaryMax: 38000,
    salaryUnit: 'hour',
    experienceLevel: 'none',
    positionsCount: 6,
    deadlineDays: 25,
    mediaKey: 'job-service',
    workLocation: 'Khu đô thị Hòa Lạc, Hà Nội',
    schedule: 'Ca 4 - 6 giờ; đăng ký tối thiểu 4 ca/tuần.',
    responsibilities: [
      'Chuẩn bị nguyên liệu và pha chế theo công thức cửa hàng.',
      'Nhận order, phục vụ khách và giữ khu vực làm việc sạch sẽ.',
      'Kiểm đếm nguyên liệu đầu/cuối ca và bàn giao quầy.',
      'Hỗ trợ đóng gói đơn mang đi và giao hàng nội khu.',
    ],
    requirements: [
      'Từ 18 tuổi, có thể làm tối thiểu 4 ca/tuần.',
      'Nhanh nhẹn, giao tiếp tốt và có trách nhiệm.',
      'Không yêu cầu kinh nghiệm; được đào tạo pha chế.',
      'Ưu tiên ứng viên có thể làm cuối tuần.',
    ],
    benefits: [
      'Thu nhập 28.000 - 38.000 đồng/giờ.',
      'Thưởng ca và hỗ trợ đồ uống trong ca.',
      'Lịch linh hoạt theo tuần.',
      'Được đào tạo kỹ năng pha chế và dịch vụ khách hàng.',
    ],
  },
  {
    slug: 'giao-vien-tieng-anh-dhqg-hoa-lac',
    title: 'Giáo viên tiếng Anh giao tiếp - ĐHQG Hòa Lạc',
    summary: 'Tuyển giáo viên tiếng Anh phụ trách lớp giao tiếp và học thuật cho sinh viên, lịch dạy linh hoạt buổi tối và cuối tuần.',
    jobType: 'part_time',
    categorySlug: 'viec-lam-giao-duc',
    areaSlug: 'dai-hoc-quoc-gia-ha-noi',
    companyName: 'Trung tâm Ngoại ngữ Hòa Lạc Campus',
    salaryMin: 250000,
    salaryMax: 450000,
    salaryUnit: 'hour',
    experienceLevel: '1_3_years',
    positionsCount: 4,
    deadlineDays: 42,
    mediaKey: 'article-education',
    workLocation: 'Khu ĐHQG Hà Nội tại Hòa Lạc',
    schedule: 'Ca tối ngày thường và cuối tuần; đăng ký lịch theo tháng.',
    responsibilities: [
      'Giảng dạy tiếng Anh giao tiếp và kỹ năng học thuật theo giáo trình.',
      'Chuẩn bị lesson plan, hoạt động lớp và bài đánh giá ngắn.',
      'Theo dõi tiến bộ và phản hồi cho học viên.',
      'Tham gia workshop chuyên môn định kỳ.',
    ],
    requirements: [
      'Tốt nghiệp ngành Ngôn ngữ Anh, Sư phạm Anh hoặc chuyên ngành phù hợp.',
      'Có chứng chỉ tiếng Anh tương đương IELTS 7.0 trở lên là lợi thế.',
      'Có kinh nghiệm đứng lớp hoặc trợ giảng.',
      'Phát âm tốt, giao tiếp tích cực và đúng giờ.',
    ],
    benefits: [
      'Thu nhập 250.000 - 450.000 đồng/giờ.',
      'Có giáo trình và trợ giảng hỗ trợ lớp đông.',
      'Lịch linh hoạt và có thưởng theo chất lượng lớp.',
      'Được tham gia đào tạo phương pháp giảng dạy.',
    ],
  },
  {
    slug: 'tro-giang-stem-sinh-vien-hoa-lac',
    title: 'Trợ giảng STEM cho sinh viên - Hòa Lạc',
    summary: 'Tuyển trợ giảng hỗ trợ lớp Robotics, Scratch và khoa học ứng dụng; phù hợp sinh viên kỹ thuật muốn tích lũy kinh nghiệm giảng dạy.',
    jobType: 'student',
    categorySlug: 'viec-lam-sinh-vien',
    areaSlug: 'hoa-lac',
    companyName: 'Hòa Lạc STEM Academy',
    salaryMin: 7000000,
    salaryMax: 10000000,
    salaryUnit: 'month',
    experienceLevel: 'none',
    positionsCount: 5,
    deadlineDays: 29,
    mediaKey: 'article-education',
    workLocation: 'Hòa Lạc, Hà Nội',
    schedule: '20 - 24 giờ/tuần, chủ yếu buổi tối và cuối tuần.',
    responsibilities: [
      'Chuẩn bị học cụ và hỗ trợ giáo viên trong giờ STEM.',
      'Hướng dẫn nhóm nhỏ thực hành Robotics và lập trình cơ bản.',
      'Kiểm tra thiết bị và ghi nhận tiến độ học sinh.',
      'Hỗ trợ hoạt động ngoại khóa và ngày hội khoa học.',
    ],
    requirements: [
      'Sinh viên CNTT, Điện tử, Cơ điện tử, Sư phạm hoặc ngành liên quan.',
      'Giao tiếp tốt và kiên nhẫn với học sinh.',
      'Biết Scratch, Arduino hoặc Robotics là lợi thế.',
      'Cam kết làm tối thiểu 4 tháng.',
    ],
    benefits: [
      'Thu nhập 7 - 10 triệu đồng/tháng theo số ca.',
      'Được đào tạo giáo án và kỹ năng đứng lớp.',
      'Có xác nhận kinh nghiệm và cơ hội lên giáo viên chính.',
      'Lịch làm việc phù hợp sinh viên.',
    ],
  },
  {
    slug: 'cong-tac-vien-content-hoa-lac',
    title: 'Cộng tác viên Content / Social - Hòa Lạc',
    summary: 'Tuyển cộng tác viên viết bài, biên tập nội dung và sản xuất social post về đời sống, dịch vụ và sự kiện tại Hòa Lạc.',
    jobType: 'student',
    categorySlug: 'viec-lam-sinh-vien',
    areaSlug: 'hoa-lac',
    companyName: 'Hòa Lạc Media Hub',
    salaryMin: 4000000,
    salaryMax: 8000000,
    salaryUnit: 'month',
    experienceLevel: 'none',
    positionsCount: 4,
    deadlineDays: 31,
    mediaKey: 'job-service',
    workLocation: 'Hòa Lạc, Hà Nội; có thể kết hợp làm từ xa.',
    schedule: 'Linh hoạt 20 giờ/tuần, họp nội dung 1 buổi cố định.',
    responsibilities: [
      'Viết bài ngắn, caption và nội dung giới thiệu dịch vụ/sự kiện.',
      'Thu thập hình ảnh, thông tin và kiểm tra nguồn trước khi biên tập.',
      'Lên lịch social post và theo dõi tương tác cơ bản.',
      'Phối hợp designer để hoàn thiện nội dung đa nền tảng.',
    ],
    requirements: [
      'Viết tiếng Việt rõ ràng, đúng chính tả và có khả năng tìm hiểu thông tin.',
      'Biết Canva hoặc công cụ thiết kế cơ bản là lợi thế.',
      'Chủ động deadline và có tinh thần kiểm chứng nguồn.',
      'Có laptop cá nhân và kết nối internet ổn định.',
    ],
    benefits: [
      'Thu nhập 4 - 8 triệu đồng/tháng tùy khối lượng.',
      'Lịch làm việc linh hoạt.',
      'Được hướng dẫn quy trình biên tập và SEO cơ bản.',
      'Có portfolio thực tế sau thời gian cộng tác.',
    ],
  },
  {
    slug: 'nhan-vien-kho-van-phu-cat',
    title: 'Nhân viên kho vận - Phú Cát',
    summary: 'Tuyển nhân viên kho vận thực hiện nhập xuất, kiểm kê, soạn hàng và phối hợp giao nhận tại khu vực Phú Cát.',
    jobType: 'service',
    categorySlug: 'viec-lam-dich-vu',
    areaSlug: 'phu-cat',
    companyName: 'Phú Cát Logistics',
    salaryMin: 10000000,
    salaryMax: 14500000,
    salaryUnit: 'month',
    experienceLevel: 'under_1_year',
    positionsCount: 8,
    deadlineDays: 27,
    mediaKey: 'job-service',
    workLocation: 'Phú Cát, khu vực Hòa Lạc, Hà Nội',
    schedule: 'Ca 8 giờ, xoay ca sáng/chiều; nghỉ luân phiên.',
    responsibilities: [
      'Nhận hàng, kiểm đếm và cập nhật chứng từ nhập kho.',
      'Soạn hàng, đóng gói và bàn giao cho bộ phận giao nhận.',
      'Kiểm kê định kỳ và báo cáo chênh lệch.',
      'Giữ khu vực kho gọn gàng và tuân thủ an toàn.',
    ],
    requirements: [
      'Tốt nghiệp THPT trở lên.',
      'Sức khỏe tốt và có thể làm việc theo ca.',
      'Biết sử dụng điện thoại/máy quét và Excel cơ bản.',
      'Có kinh nghiệm kho là lợi thế nhưng không bắt buộc.',
    ],
    benefits: [
      'Lương 10 - 14,5 triệu đồng/tháng.',
      'Phụ cấp ca, ăn giữa ca và chuyên cần.',
      'Được đào tạo quy trình kho và thiết bị quét mã.',
      'BHXH và thưởng hiệu suất theo chính sách.',
    ],
  },
  {
    slug: 'ky-thuat-vien-bao-tri-binh-yen',
    title: 'Kỹ thuật viên bảo trì cơ điện - Bình Yên',
    summary: 'Tuyển kỹ thuật viên bảo trì hệ thống điện, điều hòa, máy bơm và thiết bị cơ điện cho cụm văn phòng - xưởng tại Bình Yên.',
    jobType: 'full_time',
    categorySlug: 'viec-lam-cong-nghe-cao',
    areaSlug: 'binh-yen',
    companyName: 'Bình Yên Technical Services',
    salaryMin: 13000000,
    salaryMax: 19000000,
    salaryUnit: 'month',
    experienceLevel: 'under_1_year',
    positionsCount: 4,
    deadlineDays: 39,
    mediaKey: 'job-tech',
    workLocation: 'Bình Yên, Thạch Thất, Hà Nội',
    schedule: 'Thứ Hai - Thứ Bảy; trực kỹ thuật luân phiên theo lịch.',
    responsibilities: [
      'Kiểm tra định kỳ hệ thống điện, điều hòa, máy bơm và tủ kỹ thuật.',
      'Xử lý sự cố cơ bản và phối hợp nhà cung cấp khi cần sửa chữa chuyên sâu.',
      'Ghi nhật ký bảo trì, vật tư thay thế và tình trạng thiết bị.',
      'Thực hiện checklist an toàn trước và sau ca.',
    ],
    requirements: [
      'Tốt nghiệp trung cấp/cao đẳng Điện, Điện lạnh, Cơ điện hoặc ngành liên quan.',
      'Có kiến thức điện dân dụng/công nghiệp cơ bản.',
      'Chấp nhận ứng viên dưới 1 năm kinh nghiệm.',
      'Có tinh thần an toàn và sẵn sàng trực luân phiên.',
    ],
    benefits: [
      'Lương 13 - 19 triệu đồng/tháng.',
      'Phụ cấp trực, điện thoại và ăn trưa.',
      'Được đào tạo bảo trì hệ thống MEP thực tế.',
      'Có lộ trình lên kỹ thuật viên chính hoặc tổ trưởng.',
    ],
  },
  {
    slug: 'nhan-vien-cham-soc-khach-hang-dong-truc',
    title: 'Nhân viên chăm sóc khách hàng - Đồng Trúc',
    summary: 'Tuyển nhân viên chăm sóc khách hàng tiếp nhận yêu cầu, hỗ trợ dịch vụ và theo dõi phản hồi cho doanh nghiệp địa phương tại Đồng Trúc.',
    jobType: 'full_time',
    categorySlug: 'viec-lam-dich-vu',
    areaSlug: 'dong-truc',
    companyName: 'Đồng Trúc Service Center',
    salaryMin: 9500000,
    salaryMax: 14000000,
    salaryUnit: 'month',
    experienceLevel: 'none',
    positionsCount: 5,
    deadlineDays: 26,
    mediaKey: 'job-service',
    workLocation: 'Đồng Trúc, Thạch Thất, Hà Nội',
    schedule: 'Thứ Hai - Thứ Bảy, chia ca trong khung 08:00 - 20:00.',
    responsibilities: [
      'Tiếp nhận yêu cầu qua điện thoại, chat và trực tiếp.',
      'Phân loại yêu cầu và chuyển tới bộ phận phụ trách.',
      'Theo dõi trạng thái xử lý và chủ động phản hồi khách hàng.',
      'Cập nhật dữ liệu dịch vụ và tổng hợp phản hồi theo tuần.',
    ],
    requirements: [
      'Giao tiếp rõ ràng, lịch sự và kiên nhẫn.',
      'Sử dụng máy tính và ứng dụng văn phòng cơ bản.',
      'Không yêu cầu kinh nghiệm; được đào tạo quy trình.',
      'Có khả năng làm việc theo ca.',
    ],
    benefits: [
      'Lương 9,5 - 14 triệu đồng/tháng.',
      'Thưởng KPI dịch vụ và phụ cấp ca.',
      'Đào tạo kỹ năng chăm sóc khách hàng và CRM.',
      'Môi trường ổn định, có cơ hội lên trưởng ca.',
    ],
  },
];

function daysFromNow(days, hours = 0) {
  return new Date(Date.now() + (days * 24 + hours) * 60 * 60 * 1000);
}

function listHtml(items) {
  return `<ul>${items.map((item) => `<li>${item}</li>`).join('')}</ul>`;
}

function makeJobBody(definition) {
  return [
    `<h2>${definition.title}</h2>`,
    `<p><strong>${definition.companyName}</strong> đang tuyển ${definition.positionsCount} vị trí làm việc tại ${definition.workLocation}.</p>`,
    '<h3>Mô tả công việc</h3>',
    listHtml(definition.responsibilities),
    '<h3>Yêu cầu ứng viên</h3>',
    listHtml(definition.requirements),
    '<h3>Quyền lợi</h3>',
    listHtml(definition.benefits),
    '<h3>Thời gian làm việc</h3>',
    `<p>${definition.schedule}</p>`,
    '<h3>Cách thức ứng tuyển</h3>',
    '<p>Đây là dữ liệu mẫu phục vụ kiểm thử. Ứng viên không chuyển tiền, không cung cấp OTP và không nộp phí tuyển dụng.</p>',
  ].join('');
}

export async function seedJobShowcase({ users, categories, areas, tags, media }) {
  const result = {};
  const author = users?.admin || users?.employer;
  const rootArea = areas?.['hoa-lac'];
  const jobTag = tags?.['viec-lam'];

  if (!author || !rootArea || !jobTag) {
    throw new Error('Thiếu dữ liệu phụ thuộc để seed 15 việc làm showcase.');
  }

  for (let index = 0; index < definitions.length; index += 1) {
    const definition = definitions[index];
    const category = categories[`job:${definition.categorySlug}`];
    const area = areas[definition.areaSlug];
    const thumbnail = media?.[definition.mediaKey] || media?.['job-service'] || null;

    if (!category) {
      throw new Error(`Không tìm thấy danh mục việc làm: ${definition.categorySlug}`);
    }

    if (!area) {
      throw new Error(`Không tìm thấy khu vực việc làm: ${definition.areaSlug}`);
    }

    const areaIds = definition.areaSlug === 'hoa-lac'
      ? [area._id]
      : [area._id, rootArea._id];

    const content = await upsertContent({
      slug: definition.slug,
      contentType: 'job',
      authorId: author._id,
      title: definition.title,
      summary: definition.summary,
      bodyHtml: makeJobBody(definition),
      thumbnailMediaId: thumbnail?._id || null,
      primaryCategoryId: category._id,
      primaryAreaId: area._id,
      categoryIds: [category._id],
      areaIds,
      tagIds: [jobTag._id],
      status: 'published',
      visibility: 'public',
      publishedAt: daysFromNow(-(index + 1), -index),
      viewCount: 180 + index * 43,
      allowComments: true,
      isFeatured: index < 3,
    });

    const applicationMethod = [
      `Dữ liệu DEMO: gửi CV về ${author.email}.`,
      `Tiêu đề: [JOB-${String(index + 1).padStart(2, '0')}] ${definition.title} - Họ tên.`,
      'Không thu phí tuyển dụng, không yêu cầu chuyển tiền hoặc cung cấp mã OTP.',
    ].join(' ');

    const job = await JobPost.findOneAndUpdate(
      { contentId: content._id },
      {
        $set: {
          jobType: definition.jobType,
          companyName: definition.companyName,
          salaryMin: definition.salaryMin,
          salaryMax: definition.salaryMax,
          salaryUnit: definition.salaryUnit,
          experienceLevel: definition.experienceLevel,
          workLocation: definition.workLocation,
          applicationMethod,
          contactEmail: author.email,
          contactPhone: author.phone || '',
          deadline: daysFromNow(definition.deadlineDays),
          positionsCount: definition.positionsCount,
        },
      },
      {
        upsert: true,
        new: true,
        runValidators: true,
        setDefaultsOnInsert: true,
      },
    );

    result[definition.slug] = { content, job };
  }

  return result;
}

export { definitions as jobShowcaseDefinitions };
